/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Seguridad;

import Mantenimientos.*;
import Model.Log;
import Model.Profile;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoLog;
import dao.DaoProfile;
import dao.impl.DaoLogImpl;
import dao.impl.DaoProfileImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tool.SelectAllHeader;

/**
 *
 * @author Luigi
 */
public class Frm_Profile_Search extends javax.swing.JFrame {

    /**
     * Creates new form Frm_profile_search
     */
    Frm_MenuPrincipal menuaux=new Frm_MenuPrincipal();
    
    DaoProfile daoProfile = new DaoProfileImpl();
    List<Profile> profileList = new ArrayList<>();
    DefaultTableModel modelo;
    
    public Frm_Profile_Search(Frm_MenuPrincipal menu) {
        setTitle("Mantenimiento de Perfiles"); 
        menuaux = menu;
        initComponents();
        
        TableColumn tc = tbl_profile.getColumnModel().getColumn(4);
        tc.setHeaderRenderer(new SelectAllHeader(tbl_profile, 4));
        modelo = (DefaultTableModel) tbl_profile.getModel();
        initializeTable();
    }
    
    public Frm_Profile_Search() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_profile = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_profile = new javax.swing.JTable();
        btn_cancel = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_profile.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        tbl_profile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Estado", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_profile.getTableHeader().setReorderingAllowed(false);
        tbl_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_profileMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_profile);
        if (tbl_profile.getColumnModel().getColumnCount() > 0) {
            tbl_profile.getColumnModel().getColumn(0).setMinWidth(0);
            tbl_profile.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbl_profile.getColumnModel().getColumn(0).setMaxWidth(0);
            tbl_profile.getColumnModel().getColumn(1).setMinWidth(100);
            tbl_profile.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_profile.getColumnModel().getColumn(1).setMaxWidth(100);
            tbl_profile.getColumnModel().getColumn(2).setMinWidth(200);
            tbl_profile.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbl_profile.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        javax.swing.GroupLayout pnl_profileLayout = new javax.swing.GroupLayout(pnl_profile);
        pnl_profile.setLayout(pnl_profileLayout);
        pnl_profileLayout.setHorizontalGroup(
            pnl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_profileLayout.setVerticalGroup(
            pnl_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_profileLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_delete.setText("Cambiar Estado");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_new)
                .addGap(18, 18, 18)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_cancel)
                    .addComponent(btn_delete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void initializeTable(){
        profileList = daoProfile.profileCbo();
        String status= null;
        if(modelo!=null){
            modelo.getDataVector().removeAllElements();
            modelo.fireTableDataChanged();
        }
        try {
            for (int i = 0; i < profileList.size(); i++) {
                
                if (profileList.get(i).getStatus()==0) status = "Inactivo";
                else status = "Activo";

                Object newRow[] = {
                    profileList.get(i).getIdprofile(),
                    profileList.get(i).getName(),
                    profileList.get(i).getDescription(),
                    status,
                    false
                };
                modelo.addRow(newRow);
            }
        } catch (Exception e) {
        }
    }
    
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
        menuaux.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        menuaux.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        Frm_Profile frm_profile = new Frm_Profile(this);
        frm_profile.setVisible(true);
        frm_profile.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int idProfileDelete;
        String status;
                
        Object[] options = {"OK"};
        if (JOptionPane.showConfirmDialog(new JFrame(), "¿Desea realizar acción?",
                "Advertencias", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            for (int i = 0; i < tbl_profile.getRowCount(); i++) {
                if ((Boolean) tbl_profile.getValueAt(i, 4)) {
                    idProfileDelete = Integer.parseInt(tbl_profile.getValueAt(i, 0).toString());
                    status = tbl_profile.getValueAt(i, 3).toString();
                    if (status.equalsIgnoreCase("Activo")){
                        if (profileValidatedToDelete(idProfileDelete)) {
                            daoProfile.profileDel(idProfileDelete,0);
                            daoProfile.profileWindowsDel(idProfileDelete);
                            DaoLog daoLog =new DaoLogImpl();
                            Log logSI = null; 
                            daoLog.clientIns("Se ha desactivado el perfil " + daoProfile.profileGet(idProfileDelete).getName() ,Frm_Profile_Search.class.toString(), logSI.getIduser());
                        }
                    }else{
                        daoProfile.profileDel(idProfileDelete,1);
                        DaoLog daoLog =new DaoLogImpl();
                        Log logSI = null; 
                        daoLog.clientIns("Se ha activado el perfil " + daoProfile.profileGet(idProfileDelete).getName() ,Frm_Profile_Search.class.toString(), logSI.getIduser());
                    }
                                                                        
                    int ok_option = JOptionPane.showOptionDialog(new JFrame(), "Acciones realizadas con éxito", "Mensaje", JOptionPane.PLAIN_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                    if (ok_option == JOptionPane.OK_OPTION) {
                        initializeTable();
                    }
                }
            }
        }
        initializeTable();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_profileMouseClicked
        Profile profile = null;
        Integer idProfileSel;
        if (evt.getSource() == tbl_profile) {
            int rowSel = tbl_profile.getSelectedRow();
            int colSel = tbl_profile.getSelectedColumn();
            if (colSel != 4) {
                this.setVisible(false);
                idProfileSel = Integer.parseInt(tbl_profile.getValueAt(rowSel, 0).toString());
                profile = daoProfile.profileGet(idProfileSel);

                Frm_Profile_Assignment frm_profile_assignment = new Frm_Profile_Assignment(this, profile);
                frm_profile_assignment.setVisible(true);
                frm_profile_assignment.setLocationRelativeTo(null);
            }
        }
    }//GEN-LAST:event_tbl_profileMouseClicked
    
    private boolean profileValidatedToDelete(Integer idProfile){
        if (daoProfile.existsUserWithProfile(idProfile)){
            JOptionPane.showMessageDialog(null,"No se puede eliminar. Hay usuarios con este perfil", 
                        "Advertencias", JOptionPane.WARNING_MESSAGE);
            return false;
        } 
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frm_rack().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_profile;
    private javax.swing.JTable tbl_profile;
    // End of variables declaration//GEN-END:variables
}
