/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Reportes;

import Model.InternmentOrder;
import dao.DaoInternmentOrder;
import dao.impl.DaoInternmentOrderImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kari
 */
public class Frm_SearchIntermentOrder extends javax.swing.JFrame {

    int rowSel=0;
    int colSel=0;
    
    DaoInternmentOrder daoInternmentOrder= new DaoInternmentOrderImpl();
    DefaultTableModel modelo;
    Frm_InternmentReport menuPadre = new Frm_InternmentReport();
   
    
    public Frm_SearchIntermentOrder() {
        initComponents();
    }
    
    public Frm_SearchIntermentOrder(Frm_InternmentReport menu) {
        menuPadre = menu;
        initComponents();
        modelo = (DefaultTableModel) tbl_SearchIO.getModel();
        initilizeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SearchIO = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Selecciona el Nº de ordén:");

        tbl_SearchIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nº de ordén"
            }
        ));
        tbl_SearchIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SearchIOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_SearchIO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_SearchIOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SearchIOMouseClicked
       Integer idIO;
        if (evt.getSource() == tbl_SearchIO) {
            rowSel = tbl_SearchIO.getSelectedRow();
            colSel = tbl_SearchIO.getSelectedColumn();
         }
        idIO = Integer.parseInt(tbl_SearchIO.getValueAt(rowSel, 0).toString());
        menuPadre.setIdIO(idIO);
        menuPadre.setTextIdIO();
        menuPadre.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_tbl_SearchIOMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_SearchIO;
    // End of variables declaration//GEN-END:variables

    private void initilizeTable() {
        List<InternmentOrder> list = new ArrayList<InternmentOrder>();
        list = daoInternmentOrder.IntOrderQry();
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        try {
            for (int i = 0; i < list.size(); i++) {
                  
                Object[] fila = {list.get(i).getIdInternmentOrder()};
                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
    }
}
