/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import JasperReports.Prueba;
import Model.Movement;
import Model.Product;
import Model.Trademark;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoKardex;
import dao.DaoProducts;
import dao.DaoTrademark;
import dao.impl.DaoKardexImpl;
import dao.impl.DaoProdImpl;
import dao.impl.DaoTrademarkImpl;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tool.Validate;

/**
 *
 * @author Kari
 */
public class Frm_LibreDisponibilidadReport extends javax.swing.JFrame {

    Integer idAlmacen = 0;
    String idEan = null;
    Product producto = new Product();
    Integer idtrademark = 0;
    Frm_MenuPrincipal menuaux = new Frm_MenuPrincipal();
    List<Trademark> trademarkList = null;
    DaoTrademark daoTrademark = new DaoTrademarkImpl();
    DaoKardex daoKardex = new DaoKardexImpl();
    DaoProducts daoProducts = new DaoProdImpl();
    List<Movement> movementList = new ArrayList<>();
    List<Movement> movList = new ArrayList<>();
    List<Product> productList = new ArrayList<>();
    DefaultTableModel modelo;
    public Integer idAl;
    public Integer idP;
    public Date dateI;
    public Date dateF;
    Date dateIniSearch = null;

    /**
     * Creates new form Frm_KardexReport
     */
    public Frm_LibreDisponibilidadReport() {
        initComponents();
    }

    public Frm_LibreDisponibilidadReport(Frm_MenuPrincipal menu) {

        menuaux = menu;
        initComponents();
       dateIniSearch = new Date();
        trademarkList = daoTrademark.TrademarkQry();
        cbo_trademark.addItem("Todos");
        for (int i = 0; i < trademarkList.size(); i++) {
            cbo_trademark.addItem(trademarkList.get(i).getName());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_idProduct = new javax.swing.JTextField();
        btn_Product = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbo_trademark = new javax.swing.JComboBox();
        btn_Export = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_Report = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel3.setText("EAN 13:");

        txt_idProduct.setEnabled(false);

        btn_Product.setText("Buscar");
        btn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca:");

        cbo_trademark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trademarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(txt_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(77, 77, 77)
                .addComponent(cbo_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btn_Product))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Product)
                    .addComponent(cbo_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btn_Export.setText("Limpiar");
        btn_Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportActionPerformed(evt);
            }
        });

        btn_Cancel.setText("Cancelar");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_Report.setText("Generar Reporte");
        btn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Report)
                        .addGap(355, 355, 355)
                        .addComponent(btn_Export)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                        .addComponent(btn_Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Report)
                    .addComponent(btn_Export)
                    .addComponent(btn_Cancel))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductActionPerformed

        Frm_SearchProductLibreDisponibilidad frm_SearchProductLibreDisponibilidad = new Frm_SearchProductLibreDisponibilidad(this, idtrademark);
        frm_SearchProductLibreDisponibilidad.setVisible(true);
        frm_SearchProductLibreDisponibilidad.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ProductActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed

        menuaux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void cbo_trademarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trademarkActionPerformed
//        if (cbo_trademark.getSelectedItem() != null) {
//            for (int i = 0; i < trademarkList.size(); i++) {
//                if (cbo_trademark.getSelectedItem().equals(trademarkList.get(i).getName())) {
//                    idtrademark = trademarkList.get(i).getId_Trademark();
//                }
//            }
//        }
        
        if (cbo_trademark.getSelectedItem() != null) {
            if (cbo_trademark.getSelectedItem() != "Todos") {
                for (int i = 0; i < trademarkList.size(); i++) {
                    if (cbo_trademark.getSelectedItem().equals(trademarkList.get(i).getName())) {
                        idtrademark = trademarkList.get(i).getId_Trademark();
                    }
                }
            }
            else{
                idtrademark=null;
            }
          
        }
    }//GEN-LAST:event_cbo_trademarkActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportActionPerformed

        Prueba reporte = new Prueba();

        if (txt_idProduct.getText().length() != 0 ) {
          
           idP = producto.getIdProduct();
           reporte.mostrarReporteLibreDispConFiltro(idP);
        }
        if (txt_idProduct.getText().length() == 0 ) {
          
           dateIniSearch=new Date();
           reporte.mostrarReporteLibreDispSinFiltro( );
        }
        

    }//GEN-LAST:event_btn_ReportActionPerformed

    private void btn_ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportActionPerformed
//        Prueba exportar = new Prueba();
//        exportar.exportarReporte();
        txt_idProduct.setText(null);
    }//GEN-LAST:event_btn_ExportActionPerformed

    public void setIdWh(Integer id) {

        idAlmacen = id;
    }

 
    public void setProduct(Product p) {

        producto = p;
    }

    public void setTextIdEan() {

        txt_idProduct.setText(producto.getCodeEAN13());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Export;
    private javax.swing.JButton btn_Product;
    private javax.swing.JButton btn_Report;
    private javax.swing.JComboBox cbo_trademark;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_idProduct;
    // End of variables declaration//GEN-END:variables

    private void initializeTable() {
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        try {
            for (int i = 0; i < movementList.size(); i++) {
                Integer entrada = 0;
                Integer salida = 0;
                String entradaStr = "";
                String salidaStr = "";
                if (movementList.get(i).getType_Movement_id() == 1) {
                    entrada = (movementList.get(i).getStock_final() - movementList.get(i).getStock_inicial());
                    entradaStr = entrada.toString();
                } else {
                    salida = (movementList.get(i).getStock_inicial() - movementList.get(i).getStock_final());
                    salidaStr = salida.toString();
                }
                Object[] fila = {movementList.get(i).getIdWh(), movementList.get(i).getIdProduct(), movementList.get(i).getDate(), movementList.get(i).getType_Movement_idSubtype(),
                    entradaStr, salidaStr, movementList.get(i).getStock_inicial(), movementList.get(i).getStock_final()};

                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
    }

}
