/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reportes;

import JasperReports.Prueba;
import Model.Movement;
import Model.Product;
import Model.Trademark;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoKardex;
import dao.DaoProducts;
import dao.DaoTrademark;
import dao.impl.DaoKardexImpl;
import dao.impl.DaoProdImpl;
import dao.impl.DaoTrademarkImpl;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tool.Validate;

/**
 *
 * @author Kari
 */
public class Frm_StockReport extends javax.swing.JFrame {

    Integer idAlmacen = 0;
    String idEan = null;
    Product producto = new Product();
    Integer idtrademark = 0;
    Frm_MenuPrincipal menuaux = new Frm_MenuPrincipal();
    List<Trademark> trademarkList = null;
    DaoTrademark daoTrademark = new DaoTrademarkImpl();
    DaoKardex daoKardex = new DaoKardexImpl();
    DaoProducts daoProducts = new DaoProdImpl();
    List<Movement> movementList = new ArrayList<>();
    List<Movement> movList = new ArrayList<>();
    List<Product> productList = new ArrayList<>();
    DefaultTableModel modelo;
    public Integer idAl;
    public Integer idP;
    public Date dateI;
    public Date dateF;

    /**
     * Creates new form Frm_KardexReport
     */
    public Frm_StockReport() {
        initComponents();
    }

    public Frm_StockReport(Frm_MenuPrincipal menu) {

        menuaux = menu;
        initComponents();
        //modelo = (DefaultTableModel) tbl_Kardex.getModel();
        trademarkList = daoTrademark.TrademarkQry();
        cbo_trademark.addItem("Todos");
        for (int i = 0; i < trademarkList.size(); i++) {
            cbo_trademark.addItem(trademarkList.get(i).getName());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tbl_Wh = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Almacen = new javax.swing.JTextField();
        btn_Wh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_EAN = new javax.swing.JTextField();
        btn_Product = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbo_trademark = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        date_End = new com.toedter.calendar.JDateChooser();
        btn_Cancel = new javax.swing.JButton();
        btn_Report = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tbl_Wh.setBorder(javax.swing.BorderFactory.createTitledBorder("Almacen"));

        jLabel2.setText("Id:");

        txt_Almacen.setEnabled(false);
        txt_Almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AlmacenActionPerformed(evt);
            }
        });

        btn_Wh.setText("Buscar");
        btn_Wh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbl_WhLayout = new javax.swing.GroupLayout(tbl_Wh);
        tbl_Wh.setLayout(tbl_WhLayout);
        tbl_WhLayout.setHorizontalGroup(
            tbl_WhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbl_WhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbl_WhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbl_WhLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tbl_WhLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(txt_Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Wh)))
                .addContainerGap())
        );
        tbl_WhLayout.setVerticalGroup(
            tbl_WhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbl_WhLayout.createSequentialGroup()
                .addGroup(tbl_WhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Wh)
                    .addComponent(jLabel2)
                    .addComponent(txt_Almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel3.setText("EAN 13:");

        txt_EAN.setEnabled(false);

        btn_Product.setText("Buscar");
        btn_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca:");

        cbo_trademark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trademarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(51, 51, 51)
                .addComponent(txt_EAN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(77, 77, 77)
                .addComponent(cbo_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btn_Product)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Product)
                    .addComponent(cbo_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_EAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha"));

        jLabel5.setText("Fecha Fin:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(date_End, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12))
        );

        btn_Cancel.setText("Cancelar");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_Report.setText("Generar Reporte");
        btn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl_Wh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Report)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(366, 366, 366)
                        .addComponent(btn_Cancel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_Wh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel)
                    .addComponent(btn_Report)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_AlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AlmacenActionPerformed

    private void btn_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductActionPerformed

        Frm_SearchProductStock frm_SearchProductStock = new Frm_SearchProductStock(this, idtrademark);
        frm_SearchProductStock.setVisible(true);
        frm_SearchProductStock.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ProductActionPerformed

    private void btn_WhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WhActionPerformed

        Frm_SearchWhStock frm_SearchWhStock = new Frm_SearchWhStock(this);
        frm_SearchWhStock.setVisible(true);
        frm_SearchWhStock.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_WhActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed

        menuaux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void cbo_trademarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trademarkActionPerformed
//        if (cbo_trademark.getSelectedItem() != null) {
//            for (int i = 0; i < trademarkList.size(); i++) {
//                if (cbo_trademark.getSelectedItem().equals(trademarkList.get(i).getName())) {
//                    idtrademark = trademarkList.get(i).getId_Trademark();
//                }
//            }
//        }
        if (cbo_trademark.getSelectedItem() != null) {
            if (cbo_trademark.getSelectedItem() != "Todos") {
                for (int i = 0; i < trademarkList.size(); i++) {
                    if (cbo_trademark.getSelectedItem().equals(trademarkList.get(i).getName())) {
                        idtrademark = trademarkList.get(i).getId_Trademark();
                    }
                }
            }
            else{
                idtrademark=null;
            }
          
        }
    }//GEN-LAST:event_cbo_trademarkActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportActionPerformed

        Prueba reporte = new Prueba();
     
        Date dateEndSearch = null;
        
        if(txt_Almacen.getText().length() == 0 && txt_EAN.getText().length()==0 && date_End.getDate()==null)
        {
          
            reporte.mostrarReporteStockSinFiltro();
        }
        
        if(txt_Almacen.getText().length() != 0 && txt_EAN.getText().length()==0 && date_End.getDate()==null)
        {
            idAl = Integer.parseInt(txt_Almacen.getText());
            reporte.mostrarReporteStockXAlamacen(idAl);
        }
        if(txt_Almacen.getText().length() == 0 && txt_EAN.getText().length()!=0 && date_End.getDate()==null)
        {
            idP = producto.getIdProduct();
            reporte.mostrarReporteStockXProducto(idP);
        }
        if(txt_Almacen.getText().length() == 0 && txt_EAN.getText().length()==0 && date_End.getDate()!=null)
        {
            dateEndSearch = date_End.getDate();
            reporte.mostrarReporteStockXFecha(dateEndSearch);
        }
        if(txt_Almacen.getText().length() != 0 && txt_EAN.getText().length()!=0 && date_End.getDate()==null){
            
            
            idAl = Integer.parseInt(txt_Almacen.getText());
            idP = producto.getIdProduct();
            dateEndSearch = new Date();
            
            reporte.mostrarReporteStockXAlmacenYProducto(idAl,idP);

            
        }
        if(txt_Almacen.getText().length() != 0 && txt_EAN.getText().length()==0 && date_End.getDate()!=null){
            idAl = Integer.parseInt(txt_Almacen.getText());
            dateEndSearch = date_End.getDate();
            reporte.mostrarReporteStockXAlmacenYFecha(idAl,dateEndSearch);
        }
        
        if(txt_Almacen.getText().length() == 0 && txt_EAN.getText().length()!=0 && date_End.getDate()!=null){
            idP = producto.getIdProduct();
            dateEndSearch = date_End.getDate();
            reporte.mostrarReporteStockXProductoYFecha(idP,dateEndSearch);
        }

        if(txt_Almacen.getText().length() != 0 && txt_EAN.getText().length()!=0 && date_End.getDate()!=null){
            idAl = Integer.parseInt(txt_Almacen.getText());
            idP = producto.getIdProduct();
            dateEndSearch = date_End.getDate();
            reporte.mostrarReporteStockConFiltro(idAl,idP,dateEndSearch);
        }
        
    }//GEN-LAST:event_btn_ReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       txt_Almacen.setText(null);
       txt_EAN.setText(null);
       date_End.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setIdWh(Integer id) {

        idAlmacen = id;
    }

    public void setTextIdWh() {

        txt_Almacen.setText(idAlmacen.toString());
    }

    public void setProduct(Product p) {

        producto = p;
    }

    public void setTextIdEan() {

        txt_EAN.setText(producto.getCodeEAN13());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Product;
    private javax.swing.JButton btn_Report;
    private javax.swing.JButton btn_Wh;
    private javax.swing.JComboBox cbo_trademark;
    private com.toedter.calendar.JDateChooser date_End;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel tbl_Wh;
    private javax.swing.JTextField txt_Almacen;
    private javax.swing.JTextField txt_EAN;
    // End of variables declaration//GEN-END:variables

    private void initializeTable() {
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        try {
            for (int i = 0; i < movementList.size(); i++) {
                Integer entrada = 0;
                Integer salida = 0;
                String entradaStr = "";
                String salidaStr = "";
                if (movementList.get(i).getType_Movement_id() == 1) {
                    entrada = (movementList.get(i).getStock_final() - movementList.get(i).getStock_inicial());
                    entradaStr = entrada.toString();
                } else {
                    salida = (movementList.get(i).getStock_inicial() - movementList.get(i).getStock_final());
                    salidaStr = salida.toString();
                }
                Object[] fila = {movementList.get(i).getIdWh(), movementList.get(i).getIdProduct(), movementList.get(i).getDate(), movementList.get(i).getType_Movement_idSubtype(),
                    entradaStr, salidaStr, movementList.get(i).getStock_inicial(), movementList.get(i).getStock_final()};

                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
    }

}
