/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mantenimientos;

import Mantenimientos.Frm_PalletLocation_Search;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Mantenimientos.Frm_PalletLocation;
import Model.Distribution_Center;
import Model.LocationCell;
import Model.PalletState;
import Model.Rack;
import Model.Trademark;
import Model.Warehouse;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoDistributionCenter;
import dao.DaoPallet;
import dao.DaoPalletState;
import dao.DaoTrademark;
import dao.impl.DaoDistributionCenterImpl;
import dao.impl.DaoPalletImpl;
import dao.impl.DaoPalletStateImpl;
import dao.impl.DaoTrademarkImpl;
import java.util.*;

/** 
 *
 * @author gzavala
 */
public class Frm_PalletLocation extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Pallet
     */
    Frm_PalletLocation_Search  ventprev = new Frm_PalletLocation_Search(); 
    Integer indcentrodistribucion=0; 
    Integer indalmacen=0; 
    Integer indrack=0; 
    Integer indcelda=0; 
    Integer inddetallecelda=0; 
    Integer indmarca=0; 
    DaoDistributionCenter daoDC=new  DaoDistributionCenterImpl(); 
    DaoPallet daoPallet = new DaoPalletImpl();
    String CadenaCD="";    
    String Cadenawarehouse="";
    String Cadenarack="";
    String Cadenacelda="";
    String Cadenadetallecelda="";
    

    public void  loadcelda(String cadrack)      
    {
        DaoPallet objdao=new DaoPalletImpl();
        Integer cantreg=objdao.CeldaQry(cadrack).size();
        String[] list=new String[cantreg];
       for (int i=0; i<cantreg; i++)
        {  list[i]=objdao.CeldaQry(cadrack).get(i);
           cbo_location_cell.addItem(list[i].toString());
        } 
      cbo_location_cell.addItem(" ");
      cbo_location_cell.setSelectedIndex(cantreg);
    }       
    public void  loadrack_CD(String cadena)
    {
        DaoPallet objdao=new DaoPalletImpl();
        Integer cantreg=objdao.RackQry(cadena).size();
        Rack[] list=new Rack[cantreg];
       for (int i=0; i<cantreg; i++)
        {  list[i]=objdao.RackQry(cadena).get(i);
           cbo_rack.addItem(list[i].getIdentifier());
        } 
      cbo_rack.addItem(" ");
      cbo_rack.setSelectedIndex(cantreg);
    } 
    public void loadalmacen_CD(String CenterD)
    { 
        DaoPallet objdao=new DaoPalletImpl();
        Integer cantreg=objdao.WarehoseQry(CenterD).size();
        Warehouse[] list=new Warehouse[cantreg];
       for (int i=0; i<cantreg; i++)
        {  list[i]=objdao.WarehoseQry(CenterD).get(i);
           cbo_warehouse.addItem(list[i].getDescription());
        } 
      cbo_warehouse.addItem(" ");
      cbo_warehouse.setSelectedIndex(cantreg);
    }       
    public void cargacentrodistribucion()
    {
        DaoPallet objdao=new DaoPalletImpl();
        Integer cantreg=objdao.CDQry().size();
        Distribution_Center[] list=new Distribution_Center[cantreg];
       for (int i=0; i<cantreg; i++)
       {  list[i]=objdao.CDQry().get(i);
          cbo_center_distribution.addItem(list[i].getName());
       } 
      cbo_center_distribution.addItem(" ");
      cbo_center_distribution.setSelectedIndex(cantreg);
    }        
    public void limpiacombos()
    { cbo_center_distribution.removeAllItems();
      cbo_warehouse.removeAllItems();  
      cbo_rack.removeAllItems();  
      cbo_location_cell.removeAllItems();  
      cbo_locationcell_detail.removeAllItems();  
     }       
  
    public void load_parameter()
    { limpiacombos();
      cargacentrodistribucion();
      indcentrodistribucion=1; 
     }       
    
    public  Frm_PalletLocation()
    {
    }
    
    public Frm_PalletLocation( Frm_PalletLocation_Search ventant) {
        setTitle("Datos del Pallet");
        ventprev = ventant;
        initComponents();
        load_parameter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_pallet = new javax.swing.JPanel();
        lbl_CenterDistribution = new javax.swing.JLabel();
        cbo_center_distribution = new javax.swing.JComboBox();
        lbl_warehouse = new javax.swing.JLabel();
        cbo_warehouse = new javax.swing.JComboBox();
        lbl_rack = new javax.swing.JLabel();
        cbo_rack = new javax.swing.JComboBox();
        lbl_cell = new javax.swing.JLabel();
        cbo_location_cell = new javax.swing.JComboBox();
        lbl_date_to = new javax.swing.JLabel();
        cbo_locationcell_detail = new javax.swing.JComboBox();
        btn_search = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_pallet.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lbl_CenterDistribution.setText("Centro de Distribución");

        cbo_center_distribution.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_center_distributionItemStateChanged(evt);
            }
        });

        lbl_warehouse.setText("Almacen");

        cbo_warehouse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_warehouseItemStateChanged(evt);
            }
        });

        lbl_rack.setText("Rack");

        cbo_rack.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_rackItemStateChanged(evt);
            }
        });

        lbl_cell.setText("Celda");

        lbl_date_to.setText("Detalle Celda");

        cbo_locationcell_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_locationcell_detailActionPerformed(evt);
            }
        });

        btn_search.setLabel("Buscar");

        javax.swing.GroupLayout pnl_palletLayout = new javax.swing.GroupLayout(pnl_pallet);
        pnl_pallet.setLayout(pnl_palletLayout);
        pnl_palletLayout.setHorizontalGroup(
            pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_palletLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_CenterDistribution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_rack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_date_to, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbo_locationcell_detail, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_center_distribution, 0, 173, Short.MAX_VALUE)
                    .addComponent(cbo_rack, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_search, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_palletLayout.createSequentialGroup()
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cell, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_warehouse, 0, 160, Short.MAX_VALUE)
                            .addComponent(cbo_location_cell, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        pnl_palletLayout.setVerticalGroup(
            pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_palletLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CenterDistribution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbo_center_distribution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_warehouse)
                    .addComponent(cbo_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rack, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_rack)
                    .addComponent(lbl_cell, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_location_cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_locationcell_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_date_to))
                .addGap(18, 18, 18)
                .addComponent(btn_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_save.setText("Guardar");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_pallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_pallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_save))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        ventprev.setVisible(true);        
    }//GEN-LAST:event_formWindowClosed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        Object[] options = {"OK"};
        if ( JOptionPane.showConfirmDialog(new JFrame(), "¿Desea realizar acción?", 
            "Advertencias", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) { 
            int ok_option = JOptionPane.showOptionDialog(new JFrame(),"Se ha registrado datos del Pallet con éxito","Mensaje",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(ok_option==JOptionPane.OK_OPTION){
                ventprev.setVisible(true);
                ventprev.setLocationRelativeTo(null);
                //this.dispose();
                this.setVisible(false);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
        ventprev.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void cbo_rackItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_rackItemStateChanged

    }//GEN-LAST:event_cbo_rackItemStateChanged

    private void cbo_warehouseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_warehouseItemStateChanged

    }//GEN-LAST:event_cbo_warehouseItemStateChanged

    private void cbo_center_distributionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_center_distributionItemStateChanged

    }//GEN-LAST:event_cbo_center_distributionItemStateChanged

    private void cbo_locationcell_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_locationcell_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_locationcell_detailActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cbo_center_distribution;
    private javax.swing.JComboBox cbo_location_cell;
    private javax.swing.JComboBox cbo_locationcell_detail;
    private javax.swing.JComboBox cbo_rack;
    private javax.swing.JComboBox cbo_warehouse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_CenterDistribution;
    private javax.swing.JLabel lbl_cell;
    private javax.swing.JLabel lbl_date_to;
    private javax.swing.JLabel lbl_rack;
    private javax.swing.JLabel lbl_warehouse;
    private javax.swing.JPanel pnl_pallet;
    // End of variables declaration//GEN-END:variables
}
