/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mantenimientos;

import Model.Product;
import Model.Trademark;
import Operaciones.Frm_ProductInterment_Detail;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoProducts;
import dao.DaoTrademark;
import dao.impl.DaoProdImpl;
import dao.impl.DaoTrademarkImpl;
import java.awt.Color;
import java.awt.event.WindowListener;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class Frm_Product_Search extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Products
     */
    Frm_MenuPrincipal menuaux = new Frm_MenuPrincipal();
    DaoProducts daoProducts = new DaoProdImpl();
    DefaultTableModel modelo;
    List<Integer> idProductDeleteList = new ArrayList<Integer>();
    List<Trademark> trademarkList = null;
    DaoTrademark daoTrademark = new DaoTrademarkImpl();
    Trademark trademarkSelected;
    Integer idProdSearch;
    String nameSearch;
    Integer idTrademarkSearch;

    public Frm_Product_Search(Frm_MenuPrincipal menu) {
        setTitle("Mantenimiento de Productos");
        menuaux = menu;
        initComponents();
        modelo = (DefaultTableModel) tbl_product.getModel();
        trademarkList = daoTrademark.TrademarkQry();
        for (int i = 0; i < trademarkList.size(); i++) {
            cbo_trademark.addItem(trademarkList.get(i).getName());
        }
        initilizeTable();
    }

    public Frm_Product_Search() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        pnl_product = new javax.swing.JPanel();
        lbl_id_Product = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_trademark = new javax.swing.JLabel();
        txt_idProduct = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        cbo_trademark = new javax.swing.JComboBox();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        btn_new = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_product.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de Búsqueda"));

        lbl_id_Product.setText("ID");

        lbl_name.setText("Nombre");

        lbl_trademark.setText("Marca");

        txt_idProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idProductActionPerformed(evt);
            }
        });

        btn_search.setText("Buscar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_productLayout = new javax.swing.GroupLayout(pnl_product);
        pnl_product.setLayout(pnl_productLayout);
        pnl_productLayout.setHorizontalGroup(
            pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_productLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_productLayout.createSequentialGroup()
                        .addComponent(lbl_trademark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(392, 392, 392))
                    .addGroup(pnl_productLayout.createSequentialGroup()
                        .addComponent(lbl_id_Product)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(392, 392, 392))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_productLayout.createSequentialGroup()
                        .addGroup(pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_productLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_search))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_productLayout.createSequentialGroup()
                                .addComponent(lbl_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(192, 192, 192))))
        );
        pnl_productLayout.setVerticalGroup(
            pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_productLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_Product)
                    .addComponent(txt_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_trademark)
                    .addComponent(cbo_trademark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addGap(42, 42, 42))
        );

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Marca", "Stock Físico", "Stock Libre", "Estado", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_product);

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_delete.setText("Desactivar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_new)
                .addGap(18, 18, 18)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(pnl_product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnl_product, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_delete)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.dispose();
        menuaux.setVisible(true);
        menuaux.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        Frm_Product frmProduct = new Frm_Product(this, null);
        frmProduct.setVisible(true);
        frmProduct.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
        menuaux.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void tbl_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productMouseClicked
        Product prod = null;
        Integer idProductSel;
        if (evt.getSource() == tbl_product) {
            int rowSel = tbl_product.getSelectedRow();
            int colSel = tbl_product.getSelectedColumn();
            if (colSel != 6) {
                idProductSel = Integer.parseInt(tbl_product.getValueAt(rowSel, 0).toString());
                prod = daoProducts.ProductsGet(idProductSel);

                Frm_Product frm_product = new Frm_Product(this, prod);
                frm_product.setVisible(true);
                frm_product.setLocationRelativeTo(null);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_tbl_productMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        for (int i = 0; i < tbl_product.getRowCount(); i++) {
            if ((Boolean) tbl_product.getValueAt(i, 6)) {
                idProductDeleteList.add(Integer.parseInt(tbl_product.getValueAt(i, 0).toString()));
            }
        }
        daoProducts.ProductsDel(idProductDeleteList);
        initilizeTable();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String trademark = null;
        String status = null;
        if (txt_idProduct.getText().length() !=0) {
            idProdSearch = Integer.parseInt(txt_idProduct.getText().toString());
        } else {
            idProdSearch = 0;
        }

        String name = txt_name.getText();

        List<Product> productList = new ArrayList<Product>();
        if (cbo_trademark.getSelectedItem() != null) {
            for (int i = 0; i < trademarkList.size(); i++) {
                if (cbo_trademark.getSelectedItem().equals(trademarkList.get(i).getName())) {
                    trademarkSelected = trademarkList.get(i);
                }
            }
        }
        idTrademarkSearch = trademarkSelected.getId_Trademark();
        productList = daoProducts.ProductsSearch(idProdSearch, name, idTrademarkSearch);
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        try {
            for (int i = 0; i < productList.size(); i++) {
                for (int j = 0; j < trademarkList.size(); j++) {
                    if (trademarkList.get(j).getId_Trademark() == productList.get(i).getTrademark()) {
                        trademark = trademarkList.get(j).getName();
                    }
                }
                if (productList.get(i).getStatus() == 0) {
                    status = "Inactivo";
                } else {
                    status = "Activo";
                }
                Object[] fila = {productList.get(i).getIdProduct(), productList.get(i).getName(), trademark,
                    productList.get(i).getPhysicalStock(), productList.get(i).getFreeStock(), status, false};
                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_idProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idProductActionPerformed

    public void initilizeTable() {
        String trademark = null;
        String status = null;
        List<Product> list = new ArrayList<Product>();
        list = daoProducts.ProductsQry();
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        try {
            for (int i = 0; i < list.size(); i++) {
                for (int j = 0; j < trademarkList.size(); j++) {
                    if (trademarkList.get(j).getId_Trademark() == list.get(i).getTrademark()) {
                        trademark = trademarkList.get(j).getName();
                    }
                }
                if (list.get(i).getStatus() == 0) {
                    status = "Inactivo";
                } else {
                    status = "Activo";
                }
                Object[] fila = {list.get(i).getIdProduct(), list.get(i).getName(), trademark,
                    list.get(i).getPhysicalStock(), list.get(i).getFreeStock(), status, false};
                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cbo_trademark;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_id_Product;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_trademark;
    private javax.swing.JPanel pnl_product;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_idProduct;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
