/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mantenimientos;

import Model.Distribution_Center;
import Model.LocationCell;
import Model.PalletProduct;
import Model.Pallet_Product_Location;
import Model.Product;
import Model.Rack;
import Model.Trademark;
import Model.Warehouse;
import dao.DaoDistributionCenter;
import dao.DaoLocationCellDetail;
import dao.DaoPalletProduct;
import dao.DaoPallet_Product_Location;
import dao.DaoProducts;
import dao.DaoRack;
import dao.DaoTrademark;
import dao.DaoWH;
import dao.impl.DaoDistributionCenterImpl;
import dao.impl.DaoLocationCellDetailImpl;
import dao.impl.DaoPalletProductImpl;
import dao.impl.DaoPallet_Producto_LocationImpl;
import dao.impl.DaoProdImpl;
import dao.impl.DaoRackImpl;
import dao.impl.DaoTrademarkImpl;
import dao.impl.DaoWHImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DebugGraphics;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Luigi
 */
public class Frm_Location_Cell extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Location_Cell
     */
    public static final int NUM_CEL_DETAILS = 2;
    
    DaoDistributionCenter daoDistributionCenter = new DaoDistributionCenterImpl();
    Distribution_Center distributionCenter = null;
    
    DaoWH daoWarehouse = new DaoWHImpl();
    Warehouse warehouse = null;
    
    DaoRack daoRack = new DaoRackImpl();
    Rack rack = null;       
    
    Frm_Location_Cell_Search menu_padre = new Frm_Location_Cell_Search();
    LocationCell location_cell = null;
    
    DaoLocationCellDetail daoLocationCellDetail = new DaoLocationCellDetailImpl();    
    
    DaoPallet_Product_Location daoPalletProductLocation = new DaoPallet_Producto_LocationImpl();
    List<Pallet_Product_Location> palletProductLocationList = new ArrayList<>();
    
    DaoPalletProduct daoPalletProduct = new DaoPalletProductImpl();
    PalletProduct palletProduct = new PalletProduct();
    
    DaoProducts daoProduct = new DaoProdImpl();
    Product product = new Product();
    
    DaoTrademark daoTrademark = new DaoTrademarkImpl();
    Trademark trademark = new Trademark();
    
    public Frm_Location_Cell(Frm_Location_Cell_Search menu, LocationCell location_cell) {
        setTitle("Celdas de Ubicacion"); 
        menu_padre = menu;
        this.location_cell = location_cell;
        initComponents();                
        
        if(location_cell!=null){
            initializeForm();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_location_cell = new javax.swing.JPanel();
        lbl_warehouse = new javax.swing.JLabel();
        lbl_distribution_center = new javax.swing.JLabel();
        txt_distribution_center = new javax.swing.JTextField();
        txt_warehouse = new javax.swing.JTextField();
        txt_rack = new javax.swing.JTextField();
        lbl_rack = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        pnl_location_cell_detail = new javax.swing.JPanel();
        lbl_row = new javax.swing.JLabel();
        lbl_column = new javax.swing.JLabel();
        txt_row = new javax.swing.JTextField();
        txt_column = new javax.swing.JTextField();
        txt_state = new javax.swing.JTextField();
        lbl_state = new javax.swing.JLabel();
        pnl_detail_1 = new javax.swing.JPanel();
        lbl_trademark1 = new javax.swing.JLabel();
        lbl_product1 = new javax.swing.JLabel();
        lbl_quantity_per_box1 = new javax.swing.JLabel();
        lbl_weight_per_box1 = new javax.swing.JLabel();
        lbl_quantity_boxes_per_pallet1 = new javax.swing.JLabel();
        txt_trademark1 = new javax.swing.JTextField();
        txt_product1 = new javax.swing.JTextField();
        txt_quantity_per_box1 = new javax.swing.JTextField();
        txt_weight_per_box1 = new javax.swing.JTextField();
        txt_quantity_boxes_per_pallet1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_codean128_1 = new javax.swing.JLabel();
        pnl_detail_2 = new javax.swing.JPanel();
        lbl_trademark2 = new javax.swing.JLabel();
        lbl_product2 = new javax.swing.JLabel();
        lbl_quantity_per_box2 = new javax.swing.JLabel();
        lbl_weight_per_box2 = new javax.swing.JLabel();
        lbl_quantity_boxes_per_pallet2 = new javax.swing.JLabel();
        txt_trademark2 = new javax.swing.JTextField();
        txt_product2 = new javax.swing.JTextField();
        txt_quantity_per_box2 = new javax.swing.JTextField();
        txt_weight_per_box2 = new javax.swing.JTextField();
        txt_quantity_boxes_per_pallet2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_codean128_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_location_cell.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lbl_warehouse.setText("Almacen");

        lbl_distribution_center.setText("Centro de Distribucion");

        lbl_rack.setText("Rack");

        javax.swing.GroupLayout pnl_location_cellLayout = new javax.swing.GroupLayout(pnl_location_cell);
        pnl_location_cell.setLayout(pnl_location_cellLayout);
        pnl_location_cellLayout.setHorizontalGroup(
            pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_location_cellLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_distribution_center)
                    .addComponent(lbl_warehouse)
                    .addComponent(lbl_rack))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_distribution_center, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rack, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_location_cellLayout.setVerticalGroup(
            pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_location_cellLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_distribution_center)
                    .addComponent(txt_distribution_center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_warehouse)
                    .addComponent(txt_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        pnl_location_cell_detail.setBorder(javax.swing.BorderFactory.createTitledBorder("Posicion y Estado"));

        lbl_row.setText("Fila");

        lbl_column.setText("Columna");

        lbl_state.setText("Estado");

        javax.swing.GroupLayout pnl_location_cell_detailLayout = new javax.swing.GroupLayout(pnl_location_cell_detail);
        pnl_location_cell_detail.setLayout(pnl_location_cell_detailLayout);
        pnl_location_cell_detailLayout.setHorizontalGroup(
            pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_location_cell_detailLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_row)
                    .addComponent(lbl_state))
                .addGap(26, 26, 26)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_location_cell_detailLayout.createSequentialGroup()
                        .addComponent(txt_row, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_column)
                        .addGap(18, 18, 18)
                        .addComponent(txt_column, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_state))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnl_location_cell_detailLayout.setVerticalGroup(
            pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_location_cell_detailLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_row)
                    .addComponent(txt_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_column)
                    .addComponent(txt_column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_state))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_detail_1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle 1"));
        pnl_detail_1.setMaximumSize(new java.awt.Dimension(386, 320));
        pnl_detail_1.setMinimumSize(new java.awt.Dimension(386, 320));
        pnl_detail_1.setPreferredSize(new java.awt.Dimension(386, 320));

        lbl_trademark1.setText("Marca");

        lbl_product1.setText("Producto");

        lbl_quantity_per_box1.setText("Unidades por Empaque");

        lbl_weight_per_box1.setText("Peso Neto por Empaque");

        lbl_quantity_boxes_per_pallet1.setText("Empaques por Pallet");

        txt_trademark1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_product1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_quantity_per_box1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_weight_per_box1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_quantity_boxes_per_pallet1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setText("Unidades");

        jLabel2.setText("Kg.");

        jLabel3.setText("Empaques");

        lbl_codean128_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_codean128_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_codean128_1.setText("NO ASIGNADO");

        javax.swing.GroupLayout pnl_detail_1Layout = new javax.swing.GroupLayout(pnl_detail_1);
        pnl_detail_1.setLayout(pnl_detail_1Layout);
        pnl_detail_1Layout.setHorizontalGroup(
            pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detail_1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_trademark1)
                    .addComponent(lbl_product1)
                    .addComponent(lbl_quantity_per_box1)
                    .addComponent(lbl_weight_per_box1)
                    .addComponent(lbl_quantity_boxes_per_pallet1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_detail_1Layout.createSequentialGroup()
                        .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_weight_per_box1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(txt_quantity_boxes_per_pallet1)
                            .addComponent(txt_quantity_per_box1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_trademark1)
                        .addComponent(txt_product1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(pnl_detail_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_codean128_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_detail_1Layout.setVerticalGroup(
            pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detail_1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_codean128_1)
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_trademark1)
                    .addComponent(txt_trademark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_product1)
                    .addComponent(txt_product1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quantity_per_box1)
                    .addComponent(txt_quantity_per_box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_weight_per_box1)
                    .addComponent(txt_weight_per_box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quantity_boxes_per_pallet1)
                    .addComponent(txt_quantity_boxes_per_pallet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pnl_detail_2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle 2"));
        pnl_detail_2.setMaximumSize(new java.awt.Dimension(326, 320));
        pnl_detail_2.setMinimumSize(new java.awt.Dimension(326, 320));

        lbl_trademark2.setText("Marca");

        lbl_product2.setText("Producto");

        lbl_quantity_per_box2.setText("Unidades por Empaque");

        lbl_weight_per_box2.setText("Peso Neto por Empaque");

        lbl_quantity_boxes_per_pallet2.setText("Empaques por Pallet");

        txt_trademark2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_product2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_quantity_per_box2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_weight_per_box2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txt_quantity_boxes_per_pallet2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setText("Unidades");

        jLabel5.setText("Kg.");

        jLabel6.setText("Empaques");

        lbl_codean128_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_codean128_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_codean128_2.setText("NO ASIGNADO");

        javax.swing.GroupLayout pnl_detail_2Layout = new javax.swing.GroupLayout(pnl_detail_2);
        pnl_detail_2.setLayout(pnl_detail_2Layout);
        pnl_detail_2Layout.setHorizontalGroup(
            pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detail_2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_trademark2)
                    .addComponent(lbl_product2)
                    .addComponent(lbl_quantity_per_box2)
                    .addComponent(lbl_weight_per_box2)
                    .addComponent(lbl_quantity_boxes_per_pallet2))
                .addGap(35, 35, 35)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_trademark2)
                        .addComponent(txt_product2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(pnl_detail_2Layout.createSequentialGroup()
                        .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_quantity_boxes_per_pallet2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_weight_per_box2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(txt_quantity_per_box2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(27, 27, 27)
                        .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(pnl_detail_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_codean128_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_detail_2Layout.setVerticalGroup(
            pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_detail_2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_codean128_2)
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_trademark2)
                    .addComponent(txt_trademark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_product2)
                    .addComponent(txt_product2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quantity_per_box2)
                    .addComponent(txt_quantity_per_box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_weight_per_box2)
                    .addComponent(txt_weight_per_box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_quantity_boxes_per_pallet2)
                    .addComponent(txt_quantity_boxes_per_pallet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_location_cell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_detail_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_detail_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cancel)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnl_location_cell_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_location_cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_location_cell_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_detail_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_detail_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initializeForm() {
        String cadena = "";
        int idDC,idWH,idRack;
        
        txt_distribution_center.setEnabled(false);
        txt_warehouse.setEnabled(false);
        txt_rack.setEnabled(false);
        txt_row.setEnabled(false);
        txt_column.setEnabled(false);
        txt_state.setEnabled(false);
        
        txt_trademark1.setEnabled(false);
        txt_product1.setEnabled(false);
        txt_quantity_per_box1.setEnabled(false);
        txt_weight_per_box1.setEnabled(false);
        txt_quantity_boxes_per_pallet1.setEnabled(false);
        
        txt_trademark2.setEnabled(false);
        txt_product2.setEnabled(false);
        txt_quantity_per_box2.setEnabled(false);
        txt_weight_per_box2.setEnabled(false);
        txt_quantity_boxes_per_pallet2.setEnabled(false);
        
        idDC = location_cell.getRack_Warehouse_Distribution_Center_idDistribution_Center();
        distributionCenter = daoDistributionCenter.distribution_centerGet(idDC);
        idWH = location_cell.getRack_Warehouse_idWarehouse();
        warehouse = daoWarehouse.whGet(idWH);
        idRack = location_cell.getRack_idRack();
        rack = daoRack.rackGet(idRack);                                
        
        txt_distribution_center.setText(distributionCenter.getName());
        txt_warehouse.setText(warehouse.getDescription());
        txt_rack.setText(rack.getIdentifier());
        
        txt_row.setText(location_cell.getRow_Cell().toString().trim());
        txt_column.setText(location_cell.getColumn_Cell().toString().trim());
        if (location_cell.getLocation_State_idLocation_State()==1)
            txt_state.setText("Disponible");
        else if (location_cell.getLocation_State_idLocation_State()==2)
            txt_state.setText("No Disponible");
        else txt_state.setText("En reparacion");
        
        // busqueda de una lista de detalles con pallets_by_product para una celda de ubicacion
        cadena = " Location_Cell_Detail_idDistribution_Center = " + idDC + 
                " AND Location_Cell_Detail_Location_Cell_Rack_Warehouse_idWarehouse = " + idWH +
                " AND Location_Cell_Detail_Location_Cell_Rack_idRack = " + idRack +
                " AND Location_Cell_Detail_Location_Cell_idLocation_Cell = " + location_cell.getIdLocation_Cell() +
                " AND status = 1";
        
        palletProductLocationList = daoPalletProductLocation.GetPallet_Product_LocationWhere(cadena);
        if (palletProductLocationList!=null){
            fillDetails(palletProductLocationList);
        }
        
    }
    
    public void fillDetails (List<Pallet_Product_Location> palletProductLocationList){
        int idPalletProduct,idProduct;
        // si alguno de los dos detalles de la lista es null quiere decir que no esta en uso
        if (palletProductLocationList.size()>0 && palletProductLocationList.get(0)!=null){
            // sacar info de Pallet_By_Product para sacar el codigo ean
            idPalletProduct = palletProductLocationList.get(0).getPallet_By_Product_Pallet_idPallet();
            palletProduct = daoPalletProduct.getPalletProductById(idPalletProduct);
            // sacar info del producto
            idProduct = palletProductLocationList.get(0).getPallet_By_Product_Product_idProduct();
            product = daoProduct.ProductsGet(idProduct);
            //llenar info
            if (palletProduct!=null){
                lbl_codean128_1.setText(palletProduct.getCod_ean128().trim());                
            }
            
            if (product!=null){
                trademark = daoTrademark.TrademarkGetById(product.getTrademark());
                if (trademark!=null){
                    txt_trademark1.setText(trademark.getName());
                }                                
                txt_product1.setText(product.getName().trim());
                txt_quantity_per_box1.setText(product.getQuantityPerBox().toString());
                txt_weight_per_box1.setText(product.getWeightPerBox().toString());
                txt_quantity_boxes_per_pallet1.setText(product.getQuantityBoxesPerPallet().toString());
            }
            
        }else{
            // llenar con vacios
            lbl_codean128_1.setText("NO ASIGNADO");
            txt_trademark1.setText("NO ASIGNADO");
            txt_product1.setText("NO ASIGNADO");
            txt_quantity_per_box1.setText("0");
            txt_weight_per_box1.setText("0");
            txt_quantity_boxes_per_pallet1.setText("0");
        }
        
        if (palletProductLocationList.size()>1 && palletProductLocationList.get(1)!=null){
            // sacar info de Pallet_By_Product para sacar el codigo ean
            idPalletProduct = palletProductLocationList.get(1).getPallet_By_Product_Pallet_idPallet();
            palletProduct = daoPalletProduct.getPalletProductById(idPalletProduct);
            // sacar info del producto
            idProduct = palletProductLocationList.get(1).getPallet_By_Product_Product_idProduct();
            product = daoProduct.ProductsGet(idProduct);
            //llenar info
            if (palletProduct!=null){
                lbl_codean128_2.setText(palletProduct.getCod_ean128().trim());
            }
            
            if (product!=null){
                trademark = daoTrademark.TrademarkGetById(product.getTrademark());
                if (trademark!=null){
                    txt_trademark2.setText(trademark.getName());
                }                                
                txt_product2.setText(product.getName().trim());
                txt_quantity_per_box2.setText(product.getQuantityPerBox().toString());
                txt_weight_per_box2.setText(product.getWeightPerBox().toString());
                txt_quantity_boxes_per_pallet2.setText(product.getQuantityBoxesPerPallet().toString());
            }
            
        }else{
            // llenar con vacios
            lbl_codean128_2.setText("NO ASIGNADO");
            txt_trademark2.setText("NO ASIGNADO");
            txt_product2.setText("NO ASIGNADO");
            txt_quantity_per_box2.setText("0");
            txt_weight_per_box2.setText("0");
            txt_quantity_boxes_per_pallet2.setText("0");
        }
        
    }
    
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
        menu_padre.setVisible(true);
        menu_padre.initializeTable();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        menu_padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frm_rack().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_codean128_1;
    private javax.swing.JLabel lbl_codean128_2;
    private javax.swing.JLabel lbl_column;
    private javax.swing.JLabel lbl_distribution_center;
    private javax.swing.JLabel lbl_product1;
    private javax.swing.JLabel lbl_product2;
    private javax.swing.JLabel lbl_quantity_boxes_per_pallet1;
    private javax.swing.JLabel lbl_quantity_boxes_per_pallet2;
    private javax.swing.JLabel lbl_quantity_per_box1;
    private javax.swing.JLabel lbl_quantity_per_box2;
    private javax.swing.JLabel lbl_rack;
    private javax.swing.JLabel lbl_row;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_trademark1;
    private javax.swing.JLabel lbl_trademark2;
    private javax.swing.JLabel lbl_warehouse;
    private javax.swing.JLabel lbl_weight_per_box1;
    private javax.swing.JLabel lbl_weight_per_box2;
    private javax.swing.JPanel pnl_detail_1;
    private javax.swing.JPanel pnl_detail_2;
    private javax.swing.JPanel pnl_location_cell;
    private javax.swing.JPanel pnl_location_cell_detail;
    private javax.swing.JTextField txt_column;
    private javax.swing.JTextField txt_distribution_center;
    private javax.swing.JTextField txt_product1;
    private javax.swing.JTextField txt_product2;
    private javax.swing.JTextField txt_quantity_boxes_per_pallet1;
    private javax.swing.JTextField txt_quantity_boxes_per_pallet2;
    private javax.swing.JTextField txt_quantity_per_box1;
    private javax.swing.JTextField txt_quantity_per_box2;
    private javax.swing.JTextField txt_rack;
    private javax.swing.JTextField txt_row;
    private javax.swing.JTextField txt_state;
    private javax.swing.JTextField txt_trademark1;
    private javax.swing.JTextField txt_trademark2;
    private javax.swing.JTextField txt_warehouse;
    private javax.swing.JTextField txt_weight_per_box1;
    private javax.swing.JTextField txt_weight_per_box2;
    // End of variables declaration//GEN-END:variables
}
