/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mantenimientos;

import Model.Distribution_Center;
import Model.Rack;
import Model.Warehouse;
import Seguridad.Frm_MenuPrincipal;
import dao.impl.DaoDistributionCenterImpl;
import dao.impl.DaoRackImpl;
import dao.impl.DaoWHImpl;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luigi
 */
public class Frm_Rack_Search extends javax.swing.JFrame {

    /**
     * Creates new form Frm_rack_search
     */
    Frm_MenuPrincipal menuaux=new Frm_MenuPrincipal();
    
    int idDC_current, idWH_current;
    //Distribution_Center distribution_center_current = new Distribution_Center();
    DaoDistributionCenterImpl daoDC = new DaoDistributionCenterImpl();
    ArrayList<Distribution_Center> distribution_centers = new ArrayList<>();
    DaoWHImpl daoWH = new DaoWHImpl();
    ArrayList<Warehouse> warehouses = new ArrayList<>();
    
    DaoRackImpl daoRack = new DaoRackImpl();
    DefaultTableModel modelo;
    
    
    public Frm_Rack_Search(Frm_MenuPrincipal menu) {
        setTitle("Mantenimiento de Racks");
        menuaux = menu;
        initComponents();
        
        distribution_centers = daoDC.distribution_centerGetQry();
        for (int i = 0; i < distribution_centers.size(); i++) {
            this.cbo_distribution_center.addItem(distribution_centers.get(i).getName());
        }
        
    }
    
    public Frm_Rack_Search() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_rack = new javax.swing.JPanel();
        lbl_distribution_center = new javax.swing.JLabel();
        lbl_warehouse = new javax.swing.JLabel();
        cbo_distribution_center = new javax.swing.JComboBox();
        cbo_warehouse = new javax.swing.JComboBox();
        btn_search = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        txt_identifier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rack = new javax.swing.JTable();
        btn_new = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_rack.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de Búsqueda"));

        lbl_distribution_center.setText("Centro de Distribucion");

        lbl_warehouse.setText("Almacén");

        cbo_distribution_center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_distribution_centerActionPerformed(evt);
            }
        });

        cbo_warehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_warehouseActionPerformed(evt);
            }
        });

        btn_search.setText("Buscar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        lbl_id.setText("ID");

        javax.swing.GroupLayout pnl_rackLayout = new javax.swing.GroupLayout(pnl_rack);
        pnl_rack.setLayout(pnl_rackLayout);
        pnl_rackLayout.setHorizontalGroup(
            pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_rackLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_search)
                    .addGroup(pnl_rackLayout.createSequentialGroup()
                        .addGroup(pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_distribution_center)
                            .addComponent(lbl_warehouse)
                            .addComponent(lbl_id))
                        .addGap(45, 45, 45)
                        .addGroup(pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_distribution_center, 0, 400, Short.MAX_VALUE)
                            .addComponent(cbo_warehouse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_identifier, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        pnl_rackLayout.setVerticalGroup(
            pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_rackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_distribution_center)
                    .addComponent(cbo_distribution_center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_warehouse)
                    .addComponent(cbo_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_rackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_identifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_rack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Nro. Pisos", "Nro.Columnas", "Estado"
            }
        ));
        tbl_rack.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_rack);

        btn_new.setText("Nuevo");
        btn_new.setMaximumSize(new java.awt.Dimension(75, 23));
        btn_new.setMinimumSize(new java.awt.Dimension(75, 23));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_delete.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_rack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_rack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_delete))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
        menuaux.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed
    
    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        Frm_Rack frm_rack = new Frm_Rack(this);
        frm_rack.setVisible(true);
        frm_rack.setLocationRelativeTo(null);
        this.setVisible(false);        
    }//GEN-LAST:event_btn_newActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        menuaux.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        modelo = (DefaultTableModel) tbl_rack.getModel();
        RefreshGrid();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void cbo_distribution_centerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_distribution_centerActionPerformed
        
        //if(cbo_warehouse.getSelectedItem()!=null) this.cbo_warehouse.removeAllItems();                
        for (int i = 0; i < distribution_centers.size(); i++) {
            if (cbo_distribution_center.getSelectedItem().equals(distribution_centers.get(i).getName())) {
                this.idDC_current = distribution_centers.get(i).getIdDistribution_Center();
                warehouses = daoWH.whSearchByID(distribution_centers.get(i));
                for (int j = 0; j < warehouses.size(); j++){
                    this.cbo_warehouse.addItem(warehouses.get(j).getDescription());
                }
                break;
            }
        }
    }//GEN-LAST:event_cbo_distribution_centerActionPerformed

    private void cbo_warehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_warehouseActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < warehouses.size(); i++) {
            if (cbo_warehouse.getSelectedItem().equals(warehouses.get(i).getDescription())) {
                this.idWH_current = warehouses.get(i).getIdWarehouse();
                break;
            }
        }
    }//GEN-LAST:event_cbo_warehouseActionPerformed
    
    public void RefreshGrid(){
        List<Rack> listRack = daoRack.rackQry(idDC_current,idWH_current,txt_identifier.getText());
        int sizeListRack = listRack.size();
        if(modelo!=null){
            int a =modelo.getRowCount();
            for(int i=0; i<a; i++) modelo.removeRow(0);
        }
        try {
            for (int ind_p = 0; ind_p < sizeListRack; ind_p++) {

                Object nuevaRow[] = {
                    listRack.get(ind_p).getIdentifier(),
                    listRack.get(ind_p).getDescription(),
                    listRack.get(ind_p).getFloor_numbers(),
                    listRack.get(ind_p).getColumn_number(),
                    listRack.get(ind_p).getStatus(),};
                modelo.addRow(nuevaRow);
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frm_rack().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cbo_distribution_center;
    private javax.swing.JComboBox cbo_warehouse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_distribution_center;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_warehouse;
    private javax.swing.JPanel pnl_rack;
    private javax.swing.JTable tbl_rack;
    private javax.swing.JTextField txt_identifier;
    // End of variables declaration//GEN-END:variables
}
