/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mantenimientos;
import Mantenimientos.Frm_PalletIni;
import Model.PalletIni;
import Model.PalletState;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoPalletIni;
import dao.DaoPalletState;
import dao.impl.DaoPalletIniImpl;
import dao.impl.DaoPalletStateImpl;
import java.sql.Timestamp; 
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gzavala
 */
public class Frm_Pallet_SearchIni extends javax.swing.JFrame {

    
    /**
     * Creates new form Frm_Pallet_SearchIni
     */
    Frm_MenuPrincipal menuaux = new Frm_MenuPrincipal();

    public void inicia_estado_actividad()
    { cbo_pallet_act.removeAllItems();
      cbo_pallet_act.addItem("Activo");
      cbo_pallet_act.addItem("Inactivo");
      cbo_pallet_act.addItem(" ");
      cbo_pallet_act.setSelectedIndex(-1);
     }       
    public void inicia_estado_pallet()
    { cbo_pallet_state.removeAllItems();
      DaoPalletState objdao=new DaoPalletStateImpl(); 
      Integer cantreg= objdao.PalletStateQry().size();
      PalletState[] list=new PalletState[cantreg];
       for (int i=0; i<cantreg; i++)
       {  list[i]=objdao.PalletStateQry().get(i);
          // Se agregan los status activos
          if (list[i].getStatus()==1)
          { cbo_pallet_state.addItem(list[i].getDescription());
          }
       }   
      cbo_pallet_state.addItem(" ");
      cbo_pallet_state.setSelectedIndex(-1);
    }        
     public void limpiatabla()
     {
        DefaultTableModel model= (DefaultTableModel)tbl_pallet.getModel(); 
        Integer cantreg=0; 
        cantreg=model.getRowCount();
        for(int i=0; i<cantreg; i++)       
        { model.removeRow(cantreg-i-1);
        }   
     }        
     
     public void filtratabla(String id_pallet,String description,String actividad,String estadopallet,
                            String datefecini,String datefecfin)
     {   DaoPalletIni objdao= new DaoPalletIniImpl();
         Integer cantreg= objdao.PalletIniQry().size();
         PalletIni[] list=new PalletIni[cantreg] ;     
         DefaultTableModel model= (DefaultTableModel)tbl_pallet.getModel(); 
         for (int i=0; i<cantreg; i++)
         {  list[i]=objdao.PalletIniQry().get(i);
            //list.add(objdao.PalletQry().get(i));
             model.addRow(new Object[]{list[i].getIdpallet(), list[i].getDescription(),list[i].getStatuspallet(),
             list[i].getCreated_at(), list[i].getUpdated_at(),list[i].getUser_created(),list[i].getUser_updated(),
             list[i].getStatusactividad()} );           
         
         }   
         
          
     }        
     
    public Frm_Pallet_SearchIni(){
    }
            
    
    public Frm_Pallet_SearchIni(Frm_MenuPrincipal menu) {
        setTitle("Mantenimiento de Pallet");
        menuaux = menu;
        initComponents();
        inicia_estado_actividad();
        inicia_estado_pallet();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_pallet = new javax.swing.JPanel();
        btn_search = new javax.swing.JButton();
        cbo_pallet_act = new javax.swing.JComboBox();
        lbl_id_pallet = new javax.swing.JLabel();
        txt_id_pallet = new javax.swing.JTextField();
        lbl_status_act = new javax.swing.JLabel();
        lbl_date_from = new javax.swing.JLabel();
        dch_date_from = new com.toedter.calendar.JDateChooser();
        lbl_date_to = new javax.swing.JLabel();
        dch_date_to = new com.toedter.calendar.JDateChooser();
        lbl_status_pallet = new javax.swing.JLabel();
        cbo_pallet_state = new javax.swing.JComboBox();
        lbl_description = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        scrl_pallet = new javax.swing.JScrollPane();
        tbl_pallet = new javax.swing.JTable();
        btn_new = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_fechaini = new javax.swing.JLabel();
        lbl_fechafin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_pallet.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de Busqueda"));
        pnl_pallet.setToolTipText("");

        btn_search.setText("Buscar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        cbo_pallet_act.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbo_pallet_act.setSelectedIndex(-1);
        cbo_pallet_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_pallet_actActionPerformed(evt);
            }
        });

        lbl_id_pallet.setText("Id.Pallet");

        txt_id_pallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_palletActionPerformed(evt);
            }
        });

        lbl_status_act.setText("Estado Actividad");

        lbl_date_from.setText("Fecha Inicial");

        lbl_date_to.setText("Fecha Final");

        lbl_status_pallet.setText("Estado Pallet");

        lbl_description.setText("Descripción");

        javax.swing.GroupLayout pnl_palletLayout = new javax.swing.GroupLayout(pnl_pallet);
        pnl_pallet.setLayout(pnl_palletLayout);
        pnl_palletLayout.setHorizontalGroup(
            pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_palletLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_palletLayout.createSequentialGroup()
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_id_pallet, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_date_from)
                            .addComponent(lbl_status_act))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dch_date_from, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_id_pallet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_pallet_act, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112)
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_palletLayout.createSequentialGroup()
                                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_date_to, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_status_pallet))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dch_date_to, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_pallet_state, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_palletLayout.createSequentialGroup()
                                .addComponent(lbl_description, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_palletLayout.setVerticalGroup(
            pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_palletLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_palletLayout.createSequentialGroup()
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_pallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id_pallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_description)
                            .addComponent(txt_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lbl_date_from))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_palletLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dch_date_from, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dch_date_to, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_date_to, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(30, 30, 30)
                .addGroup(pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_status_act)
                        .addComponent(cbo_pallet_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_palletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_status_pallet)
                        .addComponent(cbo_pallet_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_search))
        );

        tbl_pallet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPallet", "Descripcion", "Estato Pallet", "Fecha Creacion", "Fecha Modificacion", "UsuarioCreacion", "Usuario Modificacion", "Estado Actividad"
            }
        ));
        scrl_pallet.setViewportView(tbl_pallet);

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_delete.setText("Eliminar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnl_pallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrl_pallet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_new)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete))
                            .addComponent(lbl_fechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(383, 383, 383)
                                .addComponent(btn_cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(lbl_fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_pallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrl_pallet, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lbl_fechaini, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new)
                    .addComponent(btn_delete)
                    .addComponent(btn_cancel))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_pallet_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_pallet_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_pallet_actActionPerformed

    private void txt_id_palletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_palletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_palletActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        Frm_PalletIni frm_pallet = new Frm_PalletIni(this);
        frm_pallet.setVisible(true);
        frm_pallet.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        menuaux.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       Integer anho1; 
       Integer anho2; 
       Integer mes1; 
       Integer mes2; 
       Integer dia1; 
       Integer dia2;
       Integer fechainicial=0; 
       Integer fechafinal=0 ; 
       String id_pallet="";
       String description="";
       String datefecini=""; 
       String datefecfin=""; 
       String actividad="";
       String estadopallet="";
       //try 
       //{    
        try 
        {  String formato = dch_date_from.getDateFormatString();
           //String formato = "YYYYMMDD";
           Date date1 = dch_date_from.getDate();
           //SimpleDateFormat sdf = new SimpleDateFormat(formato);
           anho1=dch_date_from.getCalendar().get(Calendar.YEAR);
           mes1=dch_date_from.getCalendar().get(Calendar.MONTH)+1;
           dia1=dch_date_from.getCalendar().get(Calendar.DAY_OF_MONTH);
           //datefecini = sdf.format(date1).toUpperCase();
           fechainicial=anho1*10000+mes1*100+dia1;
           datefecini=fechainicial.toString();
        } 
        catch (Exception e)   
        { JOptionPane.showMessageDialog(null, "Debe Ingresar una Fecha Inicial Valida", " Error..!!", JOptionPane.ERROR_MESSAGE);
        }
        try 
        {  String formato = dch_date_to.getDateFormatString();
           //String formato = "YYYYMMDD";
           //SimpleDateFormat sdf = new SimpleDateFormat(formato);
           anho2=dch_date_to.getCalendar().get(Calendar.YEAR);
           mes2=dch_date_to.getCalendar().get(Calendar.MONTH)+1;
           dia2=dch_date_to.getCalendar().get(Calendar.DAY_OF_MONTH);
           //datefecini = sdf.format(date1).toUpperCase();
           fechafinal=anho2*10000+mes2*100+dia2;
           datefecfin=fechafinal.toString();            
        } 
        catch (Exception e)   
        { JOptionPane.showMessageDialog(null, "Debe Ingresar una Fecha Final Valida", " Error..!!", JOptionPane.ERROR_MESSAGE);
        }

        if (fechafinal<fechainicial )
         {  JOptionPane.showMessageDialog(null, "La Fecha Final debe ser mayor o igual a la Fecha Inicial", " Error Fechas..!!", JOptionPane.INFORMATION_MESSAGE); 
          }   
        
        id_pallet= txt_id_pallet.getText().toString().trim();
        description=txt_description.getText().toString().trim();
        actividad=cbo_pallet_act.getSelectedItem().toString().trim();
        estadopallet=cbo_pallet_state.getSelectedItem().toString().trim();
        limpiatabla();
        filtratabla(id_pallet,description,actividad,estadopallet,datefecini,datefecfin);
        System.out.println("Fecha Inicial" +datefecini);
        System.out.println("Fecha Final" +datefecfin);
        
       //} catch(Exception e) 
       //   { JOptionPane.showMessageDialog(null, "Error Ingreso de Datos", " Error..!!", JOptionPane.ERROR_MESSAGE);
       //    }
       
       
    }//GEN-LAST:event_btn_searchActionPerformed

     /* @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cbo_pallet_act;
    private javax.swing.JComboBox cbo_pallet_state;
    private com.toedter.calendar.JDateChooser dch_date_from;
    private com.toedter.calendar.JDateChooser dch_date_to;
    private javax.swing.JLabel lbl_date_from;
    private javax.swing.JLabel lbl_date_to;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_fechafin;
    private javax.swing.JLabel lbl_fechaini;
    private javax.swing.JLabel lbl_id_pallet;
    private javax.swing.JLabel lbl_status_act;
    private javax.swing.JLabel lbl_status_pallet;
    private javax.swing.JPanel pnl_pallet;
    private javax.swing.JScrollPane scrl_pallet;
    private javax.swing.JTable tbl_pallet;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_id_pallet;
    // End of variables declaration//GEN-END:variables
}
