/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Mantenimientos;

import Model.Distribution_Center;
import Model.LocationCell;
import Model.LocationCellDetail;
import Model.Log;
import Model.Pallet_Product_Location;
import Model.Rack;
import Model.Warehouse;
import dao.DaoDistributionCenter;
import dao.DaoLocationCellDetail;
import dao.DaoLog;
import dao.DaoPallet_Product_Location;
import dao.DaoRack;
import dao.DaoWH;
import dao.impl.DaoDistributionCenterImpl;
import dao.impl.DaoLocationCellDetailImpl;
import dao.impl.DaoLogImpl;
import dao.impl.DaoPallet_Producto_LocationImpl;
import dao.impl.DaoRackImpl;
import dao.impl.DaoWHImpl;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luigi
 */
public class Frm_Location_Cell extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Location_Cell
     */
    public static final int NUM_CEL_DETAILS = 2;
    
    DaoDistributionCenter daoDistributionCenter = new DaoDistributionCenterImpl();
    Distribution_Center distributionCenter = null;
    
    DaoWH daoWarehouse = new DaoWHImpl();
    Warehouse warehouse = null;
    
    DaoRack daoRack = new DaoRackImpl();
    Rack rack = null;       
    
    Frm_Location_Cell_Search menu_padre = new Frm_Location_Cell_Search();
    LocationCell location_cell = null;
    
    DaoLocationCellDetail daoLocationCellDetail = new DaoLocationCellDetailImpl();
    LocationCellDetail locationCellDetailOne = new LocationCellDetail();
    LocationCellDetail locationCellDetailTwo = new LocationCellDetail();
    
    DaoPallet_Product_Location daoPalletProductLocation = new DaoPallet_Producto_LocationImpl();
    Pallet_Product_Location palletProductLocationOne = new Pallet_Product_Location();
    Pallet_Product_Location palletProductLocationTwo = new Pallet_Product_Location();
    
    public Frm_Location_Cell(Frm_Location_Cell_Search menu, LocationCell location_cell) {
        setTitle("Celdas de Ubicacion"); 
        menu_padre = menu;
        this.location_cell = location_cell;
        initComponents();                
        
        if(location_cell!=null){
            initializeForm();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_location_cell = new javax.swing.JPanel();
        lbl_warehouse = new javax.swing.JLabel();
        lbl_distribution_center = new javax.swing.JLabel();
        txt_distribution_center = new javax.swing.JTextField();
        txt_warehouse = new javax.swing.JTextField();
        txt_rack = new javax.swing.JTextField();
        lbl_rack = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        pnl_location_cell_detail = new javax.swing.JPanel();
        lbl_row = new javax.swing.JLabel();
        lbl_column = new javax.swing.JLabel();
        txt_row = new javax.swing.JTextField();
        txt_column = new javax.swing.JTextField();
        txt_state = new javax.swing.JTextField();
        lbl_state = new javax.swing.JLabel();
        pnl_detail_1 = new javax.swing.JPanel();
        pnl_detail_2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_location_cell.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lbl_warehouse.setText("Almacen");

        lbl_distribution_center.setText("Centro de Distribucion");

        lbl_rack.setText("Rack");

        javax.swing.GroupLayout pnl_location_cellLayout = new javax.swing.GroupLayout(pnl_location_cell);
        pnl_location_cell.setLayout(pnl_location_cellLayout);
        pnl_location_cellLayout.setHorizontalGroup(
            pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_location_cellLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_distribution_center)
                    .addComponent(lbl_warehouse)
                    .addComponent(lbl_rack))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_distribution_center, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rack, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_location_cellLayout.setVerticalGroup(
            pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_location_cellLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_distribution_center)
                    .addComponent(txt_distribution_center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_warehouse)
                    .addComponent(txt_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        pnl_location_cell_detail.setBorder(javax.swing.BorderFactory.createTitledBorder("Posicion y Estado"));

        lbl_row.setText("Fila");

        lbl_column.setText("Columna");

        lbl_state.setText("Estado");

        javax.swing.GroupLayout pnl_location_cell_detailLayout = new javax.swing.GroupLayout(pnl_location_cell_detail);
        pnl_location_cell_detail.setLayout(pnl_location_cell_detailLayout);
        pnl_location_cell_detailLayout.setHorizontalGroup(
            pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_location_cell_detailLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_row)
                    .addComponent(lbl_state))
                .addGap(26, 26, 26)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_location_cell_detailLayout.createSequentialGroup()
                        .addComponent(txt_row, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_column)
                        .addGap(18, 18, 18)
                        .addComponent(txt_column, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_state))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnl_location_cell_detailLayout.setVerticalGroup(
            pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_location_cell_detailLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_row)
                    .addComponent(txt_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_column)
                    .addComponent(txt_column, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_location_cell_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_state))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_detail_1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle 1"));

        javax.swing.GroupLayout pnl_detail_1Layout = new javax.swing.GroupLayout(pnl_detail_1);
        pnl_detail_1.setLayout(pnl_detail_1Layout);
        pnl_detail_1Layout.setHorizontalGroup(
            pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_detail_1Layout.setVerticalGroup(
            pnl_detail_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        pnl_detail_2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle 2"));

        javax.swing.GroupLayout pnl_detail_2Layout = new javax.swing.GroupLayout(pnl_detail_2);
        pnl_detail_2.setLayout(pnl_detail_2Layout);
        pnl_detail_2Layout.setHorizontalGroup(
            pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_detail_2Layout.setVerticalGroup(
            pnl_detail_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 692, Short.MAX_VALUE)
                .addComponent(btn_cancel)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_location_cell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnl_location_cell_detail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_detail_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(pnl_detail_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_location_cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_location_cell_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_detail_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_detail_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initializeForm() {
        txt_distribution_center.setEnabled(false);
        txt_warehouse.setEnabled(false);
        txt_rack.setEnabled(false);
        txt_row.setEnabled(false);
        txt_column.setEnabled(false);
        txt_state.setEnabled(false);
        
        distributionCenter = daoDistributionCenter.distribution_centerGet(location_cell.getRack_Warehouse_Distribution_Center_idDistribution_Center());
        warehouse = daoWarehouse.whGet(location_cell.getRack_Warehouse_idWarehouse());
        rack = daoRack.rackGet(location_cell.getRack_idRack());        
        
        
        
        txt_distribution_center.setText(distributionCenter.getName());
        txt_warehouse.setText(warehouse.getDescription());
        txt_rack.setText(rack.getIdentifier());
        
        txt_row.setText(location_cell.getRow_Cell().toString().trim());
        txt_column.setText(location_cell.getColumn_Cell().toString().trim());
        if (location_cell.getLocation_State_idLocation_State()==1)
            txt_state.setText("Disponible");
        else if (location_cell.getLocation_State_idLocation_State()==2)
            txt_state.setText("No Disponible");
        else txt_state.setText("En reparacion");
//        cbo_distribution_center.setEnabled(false);
//        for(int i=0; i<distributionCenterList.size();i++){
//            if(distributionCenterList.get(i).getIdDistribution_Center() == rack.getWarehouse_Distribution_Center_idDistribution_Center()){
//                if(cbo_distribution_center.getSelectedItem()!=null) cbo_distribution_center.removeAllItems();
//                cbo_distribution_center.addItem(distributionCenterList.get(i).getName());
//            }
//        }
//        cbo_warehouse.setEnabled(false);
//        for(int i=0; i<warehouseList.size();i++){
//            if(warehouseList.get(i).getIdWarehouse()== rack.getWarehouse_idWarehouse()){
//                if(cbo_warehouse.getSelectedItem()!=null) cbo_warehouse.removeAllItems();
//                cbo_warehouse.addItem(warehouseList.get(i).getDescription());
//            }
//        }

    }
    
    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
        menu_padre.setVisible(true);
        menu_padre.initializeTable();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        menu_padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frm_rack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frm_rack().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JLabel lbl_column;
    private javax.swing.JLabel lbl_distribution_center;
    private javax.swing.JLabel lbl_rack;
    private javax.swing.JLabel lbl_row;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_warehouse;
    private javax.swing.JPanel pnl_detail_1;
    private javax.swing.JPanel pnl_detail_2;
    private javax.swing.JPanel pnl_location_cell;
    private javax.swing.JPanel pnl_location_cell_detail;
    private javax.swing.JTextField txt_column;
    private javax.swing.JTextField txt_distribution_center;
    private javax.swing.JTextField txt_rack;
    private javax.swing.JTextField txt_row;
    private javax.swing.JTextField txt_state;
    private javax.swing.JTextField txt_warehouse;
    // End of variables declaration//GEN-END:variables
}
