/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Operaciones;

import Model.InternmentOrder;
import Model.InternmentOrderDetail;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoInternmentOrderDetail;
import dao.impl.DaoInternmentOrderDetailImpl;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tool.SelectAllHeader;

/**
 *
 * @author Gustavo
 */
public class Frm_IntermentOrder_Detail extends javax.swing.JFrame {

    /**
     * Creates new form Frm_IntermentOrder_Detail
     */
    Frm_InternmentOrder_Search menupadre = new Frm_InternmentOrder_Search();
    DaoInternmentOrderDetail daoIntOrdDetail = new DaoInternmentOrderDetailImpl();
    DefaultTableModel modelo = new DefaultTableModel();
    InternmentOrder intOrder;
    List<Integer> idIntOrdDetailList = new ArrayList<>();

    public Frm_IntermentOrder_Detail(Frm_InternmentOrder_Search menu, InternmentOrder intOrd) {
        menupadre = menu;
        setTitle("Detalle de Orden de Internamiento");
        intOrder = intOrd;
        initComponents();
        TableColumn tc = tbl_orderDetail.getColumnModel().getColumn(5);
        tc.setHeaderRenderer(new SelectAllHeader(tbl_orderDetail, 5));
        modelo = (DefaultTableModel) tbl_orderDetail.getModel();
        if (intOrd != null) {
            initializeForm();
        }
    }

    public Frm_IntermentOrder_Detail() {
    }

    private void initializeForm() {
        String status = null;
        txt_idOrder.setText(intOrder.getIdInternmentOrder().toString());
        txt_idOrder.setEnabled(false);
        txt_dateOrder.setText(intOrder.getDate().toString());
        txt_dateOrder.setEnabled(false);
        if (intOrder.getStatus() == 1) {
            status = "Pendiente";
        }
        if (intOrder.getStatus() == 2) {
            status = "Internado";
            tbl_orderDetail.setEnabled(false);
        }
        if (intOrder.getStatus() == 0) {
            status = "Inactivo";
            tbl_orderDetail.setEnabled(false);
        }
        
        txt_state.setText(status);
        initializeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_generalData = new javax.swing.JPanel();
        lbl_idOrder = new javax.swing.JLabel();
        txt_idOrder = new javax.swing.JTextField();
        lbl_date = new javax.swing.JLabel();
        txt_dateOrder = new javax.swing.JTextField();
        lbl_state = new javax.swing.JLabel();
        txt_state = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_orderDetail = new javax.swing.JTable();
        btn_Cancel = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle de Orden de Internamiento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_generalData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lbl_idOrder.setText("Número de Orden");

        txt_idOrder.setEnabled(false);

        lbl_date.setText("Fecha de Orden");

        txt_dateOrder.setEnabled(false);

        lbl_state.setText("Estado");

        txt_state.setEnabled(false);

        javax.swing.GroupLayout pnl_generalDataLayout = new javax.swing.GroupLayout(pnl_generalData);
        pnl_generalData.setLayout(pnl_generalDataLayout);
        pnl_generalDataLayout.setHorizontalGroup(
            pnl_generalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_generalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_generalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idOrder)
                    .addComponent(lbl_date))
                .addGap(18, 18, 18)
                .addGroup(pnl_generalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_idOrder)
                    .addComponent(txt_dateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(131, 131, 131)
                .addComponent(lbl_state)
                .addGap(37, 37, 37)
                .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_generalDataLayout.setVerticalGroup(
            pnl_generalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_generalDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_generalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idOrder)
                    .addComponent(txt_idOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_state)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_generalDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_date)
                    .addComponent(txt_dateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Orden"));

        tbl_orderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° Linea", "ID Producto", "Nombre", "Cantidad Pallets", "Estado", "Seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_orderDetail);

        btn_Cancel.setText("Cancelar");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        btn_delete.setText("Desactivar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Cancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cancel)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_generalData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_generalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        menupadre.setVisible(true);
        this.dispose();
        menupadre.initializeTable();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        menupadre.setVisible(true);
        this.dispose();
        menupadre.initializeTable();
    }//GEN-LAST:event_formWindowClosed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        for (int i = 0; i < tbl_orderDetail.getRowCount(); i++) {
            if ((Boolean) tbl_orderDetail.getValueAt(i, 5)) {
                idIntOrdDetailList.add(Integer.parseInt(tbl_orderDetail.getValueAt(i, 0).toString()));
            }
        }
        daoIntOrdDetail.IntOrderDetailsDel(intOrder.getIdInternmentOrder(), idIntOrdDetailList);
        Object[] options = {"OK"};
        if (JOptionPane.showConfirmDialog(new JFrame(), "¿Desea realizar acción?",
                "Advertencias", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int ok_option = JOptionPane.showOptionDialog(new JFrame(), "Se ha desactivado las linea de detalle seleccionadas con éxito", "Mensaje", JOptionPane.PLAIN_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            if (ok_option == JOptionPane.OK_OPTION) {
                initializeTable();
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    public void initializeTable() {
        String status = null;
        List<InternmentOrderDetail> intOrderDetaillist = new ArrayList<InternmentOrderDetail>();
        intOrderDetaillist = daoIntOrdDetail.IntOrderDetailQry(intOrder.getIdInternmentOrder());
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        try {
            for (int i = 0; i < intOrderDetaillist.size(); i++) {
                if (intOrderDetaillist.get(i).getStatus() == 1) {
                    status = "Activo";
                } else {
                    status = "Inactivo";
                }
                if (intOrderDetaillist.get(i).getStatus() == 1) {
                    Object[] fila = {intOrderDetaillist.get(i).getIdInternmentOrderDetail(),
                        intOrderDetaillist.get(i).getProduct().getIdProduct(),
                        intOrderDetaillist.get(i).getProduct().getName(),
                        intOrderDetaillist.get(i).getQuantityPallets(),
                        status, false};
                    modelo.addRow(fila);
                }
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_idOrder;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JPanel pnl_generalData;
    private javax.swing.JTable tbl_orderDetail;
    private javax.swing.JTextField txt_dateOrder;
    private javax.swing.JTextField txt_idOrder;
    private javax.swing.JTextField txt_state;
    // End of variables declaration//GEN-END:variables
}
