/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Operaciones;

import Model.Client;
import Model.Driver;
import Model.Trademark;
import Seguridad.Frm_MenuPrincipal;
import dao.DaoClient;
import dao.DaoDriver;
import dao.DaoRequestOrder;
import dao.DaoTrademark;
import dao.impl.DaoClientImpl;
import dao.impl.DaoDriverImpl;
import dao.impl.DaoRequestOrderImpl;
import dao.impl.DaoTrademarkImpl;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class Frm_MassiveLoad extends javax.swing.JFrame {

    /**
     * Creates new form Frm_MassiveLoad
     */
    Frm_MenuPrincipal menuPadre;
    String directoryClient = null;
    String directoryDriver = null;
    String directoryTrademark = null;
    DaoClient daoClient = new DaoClientImpl();
    DaoDriver daoDriver = new DaoDriverImpl();
    DaoTrademark daoTrademark = new DaoTrademarkImpl();

    public Frm_MassiveLoad(Frm_MenuPrincipal menu) {
        menuPadre = menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_fileClient = new javax.swing.JTextField();
        btn_selectFileClient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_selectFileDriver = new javax.swing.JButton();
        txt_fileDriver = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_fileTrademark = new javax.swing.JTextField();
        btn_selectFileTrademark = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carga Masiva de Datos");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección de Archivos"));

        jLabel1.setText("Archivo de Clientes");

        btn_selectFileClient.setText("Seleccionar");
        btn_selectFileClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectFileClientActionPerformed(evt);
            }
        });

        jLabel2.setText("Archivo Conductores");

        btn_selectFileDriver.setText("Seleccionar");
        btn_selectFileDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectFileDriverActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivo Marcas");

        btn_selectFileTrademark.setText("Seleccionar");
        btn_selectFileTrademark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectFileTrademarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_fileDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(txt_fileClient)
                    .addComponent(txt_fileTrademark))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_selectFileClient))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_selectFileDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_selectFileTrademark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_fileClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selectFileClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_selectFileDriver)
                    .addComponent(txt_fileDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_fileTrademark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selectFileTrademark))
                .addContainerGap(371, Short.MAX_VALUE))
        );

        btn_Save.setText("Cargar archivos");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancel)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Save)
                    .addComponent(btn_cancel))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        menuPadre.setVisible(true);
        menuPadre.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_selectFileClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectFileClientActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione archivo");
        fileChooser.showDialog(this, null);
        try {
            directoryClient = fileChooser.getSelectedFile().getAbsolutePath();
            txt_fileClient.setText(directoryClient);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_selectFileClientActionPerformed

    private void btn_selectFileDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectFileDriverActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione archivo");
        fileChooser.showDialog(this, null);
        try {
            directoryDriver = fileChooser.getSelectedFile().getAbsolutePath();
            txt_fileDriver.setText(directoryDriver);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_selectFileDriverActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        Object[] options = {"OK"};
        int ok_option;
        if (directoryClient == null && directoryDriver == null && directoryTrademark == null) {
            ok_option = JOptionPane.showOptionDialog(new JFrame(), "Seleccione un archivo", "Mensaje", JOptionPane.PLAIN_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        } else {
            if (JOptionPane.showConfirmDialog(new JFrame(), "¿Desea realizar acción?",
                    "Advertencias", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (directoryClient != null) {
                    loadClient();
                }
                if (directoryDriver != null) {
                    loadDriver();
                }
                if (directoryTrademark != null){
                    loadTrademark();
                }
                
                    ok_option = JOptionPane.showOptionDialog(new JFrame(), "Se ha cargado los archivos con éxito", "Mensaje", JOptionPane.PLAIN_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                }
            }
        
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_selectFileTrademarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectFileTrademarkActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione archivo");
        fileChooser.showDialog(this, null);
        try {
            directoryTrademark = fileChooser.getSelectedFile().getAbsolutePath();
            txt_fileTrademark.setText(directoryTrademark);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_selectFileTrademarkActionPerformed

    public void loadClient() {
        String line = null;

        File file = new File(directoryClient);
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader(file));
            reader.readLine();

            while ((line = reader.readLine()) != null) {
                Client client = new Client();
                String[] lineArray = line.split(",");
//                        client.setIdClient(Integer.parseInt(lineArray[0]));
                client.setRuc(lineArray[1]);
                client.setName(lineArray[2]);
                client.setAddress(lineArray[3]);
                client.setPriority(Integer.parseInt(lineArray[4]));
                client.setPos_x(Integer.parseInt(lineArray[5]));
                client.setPos_y(Integer.parseInt(lineArray[6]));
                client.setStatus(Integer.parseInt(lineArray[7]));
                daoClient.clientIns(client);
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    
                }
            }
        }
    }

    public void loadDriver() {
        String line = null;
        Integer maxId = daoDriver.driverGetMaxId();
        File file = new File(directoryDriver);
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader(file));
            reader.readLine();

            while ((line = reader.readLine()) != null) {
                Driver driver = new Driver();
                String[] lineArray = line.split(",");
                driver.setIdDriver(maxId);
                driver.setName(lineArray[1]);
                driver.setStatus(Integer.parseInt(lineArray[2]));
                daoDriver.driverIns(driver);
                maxId++;
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    
                }
            }
        }
    }
    
    public void loadTrademark() {
        String line = null;
        Integer maxId = daoTrademark.trademarkGetMaxId();
        File file = new File(directoryTrademark);
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader(file));
            reader.readLine();

            while ((line = reader.readLine()) != null) {
                Trademark trademark = new Trademark();
                String[] lineArray = line.split(",");
                trademark.setId_Trademark(maxId);
                trademark.setName(lineArray[1]);
                daoTrademark.trademarkIns(trademark);
                maxId++;
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_selectFileClient;
    private javax.swing.JButton btn_selectFileDriver;
    private javax.swing.JButton btn_selectFileTrademark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_fileClient;
    private javax.swing.JTextField txt_fileDriver;
    private javax.swing.JTextField txt_fileTrademark;
    // End of variables declaration//GEN-END:variables
}
