/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Operaciones;

import Model.Product;
import dao.DaoProducts;
import dao.DaoTrademark;
import dao.impl.DaoProdImpl;
import dao.impl.DaoTrademarkImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class Frm_SearchProduct extends javax.swing.JFrame {

    /**
     * Creates new form Frm_SearchProduct
     */
    Frm_adjustManual menuPadre;
    DefaultTableModel modelo = new DefaultTableModel();
    DaoProducts daoProducts = new DaoProdImpl();
    DaoTrademark daoTrademark = new DaoTrademarkImpl();

    public Frm_SearchProduct(Frm_adjustManual menu) {
        this.setTitle("Seleccionar Pallet disponible");
        menuPadre = menu;
        initComponents();
        modelo = (DefaultTableModel) tbl_products.getModel();
        initializeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Producto"));

        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código Pallet", "EAN13", "Nombre", "Marca"
            }
        ));
        tbl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_products);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        menuPadre.setVisible(true);
        menuPadre.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void tbl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productsMouseClicked
        Product prod = null;
        if (evt.getSource() == tbl_products) {
            int rowSel = tbl_products.getSelectedRow();
            menuPadre.setTxtCodProduct(tbl_products.getValueAt(rowSel, 0).toString());
            menuPadre.setTxtEAN13(tbl_products.getValueAt(rowSel, 1).toString());
            menuPadre.setTxtName(tbl_products.getValueAt(rowSel, 2).toString());
            menuPadre.setTxtTrademark(tbl_products.getValueAt(rowSel, 3).toString());
            menuPadre.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_tbl_productsMouseClicked

    public void initializeTable() {
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        List<Product> productList = daoProducts.ProductsQry();
        try {
            for (int i = 0; i < productList.size(); i++) {
                String trademark = daoTrademark.TrademarkGetById(productList.get(i).getTrademark()).getName();
                Object[] fila = {productList.get(i).getIdProduct(), productList.get(i).getCodeEAN13(),
                    productList.get(i).getName(), trademark};
                modelo.addRow(fila);
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_products;
    // End of variables declaration//GEN-END:variables
}
