/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Operaciones;

import Model.Client;
import dao.DaoClient;
import dao.impl.DaoClientImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Miguel
 */
public class Frm_Client_Get extends javax.swing.JFrame {
    Frm_RequestOrder_Search frm_rosAux = new Frm_RequestOrder_Search();
    Frm_PickingOrder_Search frm_posAux = new Frm_PickingOrder_Search();  
    Frm_DispatchOrder_Search frm_dosAux = new Frm_DispatchOrder_Search();
    DaoClient daoClient = new DaoClientImpl();
    int flag_window;
    DefaultTableModel model = new DefaultTableModel();
    List<Client> listClient = new ArrayList<>();
    /**
     * Creates new form Frm_Client_Get
     */
    public Frm_Client_Get() {
        initComponents();
    }
    
    public Frm_Client_Get(Frm_RequestOrder_Search frm_ros){
        frm_rosAux = frm_ros;
        initComponents();
        model = (DefaultTableModel) table_client.getModel();
        refreshGrid();
        fillTable();
        flag_window = 1;
    }
    
    public Frm_Client_Get(Frm_PickingOrder_Search frm_pos){
        frm_posAux = frm_pos;
        initComponents();
        model = (DefaultTableModel) table_client.getModel();
        refreshGrid();
        fillTable();
        flag_window=2;
    }
    
    public Frm_Client_Get(Frm_DispatchOrder_Search frm_dos){
        frm_dosAux = frm_dos;
        initComponents();
        model = (DefaultTableModel) table_client.getModel();
        refreshGrid();
        fillTable();
        flag_window=3;
    }
    
    public void fillTable(){
        Object[] options = {"OK"};
        listClient = daoClient.clientQry();
        if(listClient == null){
           int ok_option = JOptionPane.showOptionDialog(new JFrame(),"No existen clientes registrados.","Mensaje",JOptionPane.PLAIN_MESSAGE,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
           if(ok_option == JOptionPane.OK_OPTION){
               if(flag_window == 1){
                    frm_rosAux.setVisible(true);
                    this.dispose();
                }else if(flag_window == 2){
                    frm_posAux.setVisible(true);
                    this.dispose();
                }else{
                    frm_dosAux.setVisible(true);
                    this.dispose();
                }
           }
        }else{
            int size = listClient.size();
            for(int i=0;i<size;i++){
                Object[] fila = {listClient.get(i).getRuc(),listClient.get(i).getName()};
                model.addRow(fila);
            }
        }
    }
    
    public void refreshGrid(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_client = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        table_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "Nombre"
            }
        ));
        table_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_client);

        jLabel1.setText("Seleccione un cliente:");

        btn_Cancel.setText("Cancelar");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Cancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Cancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(flag_window == 1){
            frm_rosAux.setVisible(true);
            this.dispose();
        }else if(flag_window == 2){
            frm_posAux.setVisible(true);
            this.dispose();
        }else{
            frm_dosAux.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        if(flag_window == 1){
            frm_rosAux.setVisible(true);
            this.dispose();
        }else if(flag_window == 2){
            frm_posAux.setVisible(true);
            this.dispose();
        }else{
            frm_dosAux.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void table_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clientMouseClicked
        // TODO add your handling code here:
         if(evt.getSource()==table_client){
            int rowSel = table_client.getSelectedRow();
            int colSel = table_client.getSelectedColumn();
            if (colSel==0){
              Client client = listClient.get(rowSel);
                if(flag_window == 1){
                    frm_rosAux.setClient(client);
                    frm_rosAux.setVisible(true);
                    this.dispose();
                }else if(flag_window == 2){
                    frm_posAux.setVisible(true);
                    this.dispose();
                }else{
                    frm_dosAux.setClient(client);
                    frm_dosAux.setVisible(true);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_table_clientMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_client;
    // End of variables declaration//GEN-END:variables
}
