/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Operaciones;

import Model.Client;
import Model.PalletProduct;
import Model.Pallet_Product_Location;
import Model.PickingOrder;
import Model.PickingOrderDetail;
import Model.Product;
import Model.RequestOrder;
import dao.DaoClient;
import dao.DaoPallet;
import dao.DaoPalletProduct;
import dao.DaoPallet_Product_Location;
import dao.DaoProducts;
import dao.DaoRequestOrder;
import dao.impl.DaoClientImpl;
import dao.impl.DaoPalletImpl;
import dao.impl.DaoPalletProductImpl;
import dao.impl.DaoPallet_Producto_LocationImpl;
import dao.impl.DaoProdImpl;
import dao.impl.DaoRequestOrderImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Miguel
 */
public class Frm_RequestOrder_Preview extends javax.swing.JFrame {
    Frm_RequestOrder_Detail frm_rodAux = new Frm_RequestOrder_Detail();
    PickingOrder poAux = new PickingOrder();
    DaoClient daoClient = new DaoClientImpl();
    DaoRequestOrder daoRequestOrder = new DaoRequestOrderImpl();
    List<PickingOrderDetail> listAux =  new ArrayList<>();
    DaoPallet_Product_Location daoPalletProductLocation = new DaoPallet_Producto_LocationImpl();
    DaoPalletProduct daoPalletProduct = new DaoPalletProductImpl();
    DaoPallet daoPallet = new DaoPalletImpl();
    DaoProducts daoProduct = new DaoProdImpl();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form Frm_RequestOrder_Preview
     */
    public Frm_RequestOrder_Preview(Frm_RequestOrder_Detail frm_rod) {
        frm_rodAux = frm_rod;
        setTitle("ORDEN DE ENTREGA GENERADA");
        initComponents();
    }
    
    public Frm_RequestOrder_Preview(PickingOrder po, List<PickingOrderDetail> list) {
        
        setTitle("ORDEN DE ENTREGA GENERADA");
        initComponents();
        model = (DefaultTableModel) table_products.getModel();
        poAux=po;
        listAux=list;
        fillData();
    }

    private void fillData(){
        txt_request_order.setText(poAux.getIdRequest_Order().toString());
        txt_picking_order.setText(poAux.getIdPickingOrder().toString());
        RequestOrder ro = new RequestOrder();
        ro = daoRequestOrder.requestOrderGet(poAux.getIdRequest_Order());
        Client client = new Client();
        if(ro!=null){   
            client = ro.getClient();
            txt_client_id.setText(client.getRuc());
            txt_client_name.setText(client.getName());
        }
        fillTable();
    }
    
    private void fillTable(){
        int size = listAux.size();
        System.out.println("SASDg: "+size);
        for(int i=0;i<size;i++){
            Pallet_Product_Location ppl = daoPalletProductLocation.daoPallet_Product_LocationGet(listAux.get(i).getIdPallet_By_Product_By_Location_Cell_Detail());
            List<PalletProduct> pp = daoPalletProduct.GetPalletProductList("WHERE Pallet_idPallet="+ppl.getPallet_By_Product_Pallet_idPallet());
            int sizepp = pp.size();
            for(int j=0;j<sizepp;j++){
                String ean128 = pp.get(j).getCod_ean128();
                Product prod = daoProduct.ProductsGet(pp.get(j).getIdproduct());
                Object[] fila = {ean128,prod.getName()};
                 model.addRow(fila);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_order = new javax.swing.JPanel();
        lbl_request_order = new javax.swing.JLabel();
        lbl_picking = new javax.swing.JLabel();
        lbl_client = new javax.swing.JLabel();
        txt_request_order = new javax.swing.JTextField();
        txt_picking_order = new javax.swing.JTextField();
        txt_client_id = new javax.swing.JTextField();
        txt_client_name = new javax.swing.JTextField();
        pnl_products = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_products = new javax.swing.JTable();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnl_order.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lbl_request_order.setText("Orden de Pedido:");

        lbl_picking.setText("Orden de Entrega (Picking):");

        lbl_client.setText("Cliente:");

        txt_request_order.setEditable(false);

        txt_picking_order.setEditable(false);

        txt_client_id.setEditable(false);

        txt_client_name.setEditable(false);

        javax.swing.GroupLayout pnl_orderLayout = new javax.swing.GroupLayout(pnl_order);
        pnl_order.setLayout(pnl_orderLayout);
        pnl_orderLayout.setHorizontalGroup(
            pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_orderLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_request_order)
                    .addComponent(lbl_picking)
                    .addComponent(lbl_client))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_orderLayout.createSequentialGroup()
                        .addComponent(txt_client_id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_client_name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_picking_order, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(txt_request_order, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        pnl_orderLayout.setVerticalGroup(
            pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_orderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_request_order)
                    .addComponent(txt_request_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_picking)
                    .addComponent(txt_picking_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_client)
                    .addComponent(txt_client_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_client_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnl_products.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        table_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Pallet", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_products);

        javax.swing.GroupLayout pnl_productsLayout = new javax.swing.GroupLayout(pnl_products);
        pnl_products.setLayout(pnl_productsLayout);
        pnl_productsLayout.setHorizontalGroup(
            pnl_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        pnl_productsLayout.setVerticalGroup(
            pnl_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_productsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_exit.setText("Salir");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_products, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_order, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_exit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exit)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_client;
    private javax.swing.JLabel lbl_picking;
    private javax.swing.JLabel lbl_request_order;
    private javax.swing.JPanel pnl_order;
    private javax.swing.JPanel pnl_products;
    private javax.swing.JTable table_products;
    private javax.swing.JTextField txt_client_id;
    private javax.swing.JTextField txt_client_name;
    private javax.swing.JTextField txt_picking_order;
    private javax.swing.JTextField txt_request_order;
    // End of variables declaration//GEN-END:variables
}
